--
-- SPDX-FileCopyrightText: (c) 2026 Ring Zero Desenvolvimento de Software LTDA
-- SPDX-License-Identifier: MIT OR GPL-2.0-only
--
-- Input for autogen.lua. A spec is one of two kinds. A constant spec carries
-- a `prefix` and produces a table of integer constants (keyed by the constant
-- name with `prefix` stripped, unless `strip` is false). A struct spec carries `struct` and `fields`
-- and produces a layout descriptor (per-field offset/size/signedness + total
-- size); `lib/struct.lua` turns that into a `string.pack` codec. Each entry
-- feeds one autogen/linux/<module>.lua.
--
-- @field header path relative to $(KBUILD)/include
-- @field module name of the resulting Lua module
-- @field desc   short LDoc description used by autogen/ldoc.lua
-- @field prefix constant prefix (constant specs)
-- @field strip  false keeps `prefix` in the keys (constant specs)
-- @field struct kernel struct name (struct specs)
-- @field as     Lua key for the layout (struct specs); defaults to `struct`
-- @field fields the struct's scalar fields (struct specs); order is free
--   (sorted by offset), but list them all, as gaps become padding and
--   non-scalar fields fail the build

return {
	{ header = "uapi/linux/if_ether.h", prefix = "ETH_P_", module = "eth",
		desc = "Ethernet protocol IDs." },
	{ header = "uapi/linux/if_arp.h", prefix = "ARPHRD_", module = "arphrd",
		desc = "Network device hardware types (ARPHRD_*)." },
	{ header = "uapi/linux/if_packet.h", prefix = "PACKET_", module = "pkttype",
		desc = "Packet types (PACKET_HOST, ...).",
		include = { "HOST", "BROADCAST", "MULTICAST", "OTHERHOST", "OUTGOING", "LOOPBACK", "USER", "KERNEL" } },
	{ header = "linux/stat.h", prefix = "S_", module = "stat",
		desc = "File mode bits." },
	{ header = "linux/fsnotify_backend.h", prefix = "FS_", module = "fsnotify",
		desc = "Filesystem notification event masks and flags.",
		include = { "ACCESS", "MODIFY", "ATTRIB", "CLOSE_WRITE", "CLOSE_NOWRITE", "OPEN",
			"MOVED_FROM", "MOVED_TO", "CREATE", "DELETE", "DELETE_SELF", "MOVE_SELF",
			"OPEN_EXEC", "UNMOUNT", "Q_OVERFLOW", "ERROR",
			"OPEN_PERM", "ACCESS_PERM", "OPEN_EXEC_PERM",
			"EVENT_ON_CHILD", "RENAME", "ISDIR" } },
	{ header = "uapi/linux/signal.h", prefix = "SIG", module = "signal",
		desc = "POSIX signal numbers." },
	{ header = "linux/notifier.h", prefix = "NOTIFY_", module = "notify",
		desc = "Return codes for kernel notifier chains." },
	{ header = "linux/notifier.h", prefix = "KBD_", module = "kbd",
		desc = "Keyboard notifier event types." },
	{ header = "linux/vt.h", prefix = "VT_", module = "vt",
		desc = "Virtual terminal notifier event types.",
		include = { "ALLOCATE", "DEALLOCATE", "WRITE", "UPDATE", "PREWRITE" } },
	{ header = "linux/netdevice.h", prefix = "NETDEV_", module = "netdev",
		desc = "Network device notifier event types.",
		include = { "UP", "DOWN", "REBOOT", "CHANGE", "REGISTER", "UNREGISTER", "CHANGEMTU",
			"CHANGEADDR", "PRE_CHANGEADDR", "GOING_DOWN", "CHANGENAME", "FEAT_CHANGE",
			"BONDING_FAILOVER", "PRE_UP", "PRE_TYPE_CHANGE", "POST_TYPE_CHANGE", "POST_INIT",
			"PRE_UNINIT", "RELEASE", "NOTIFY_PEERS", "JOIN", "CHANGEUPPER", "RESEND_IGMP",
			"PRECHANGEMTU", "CHANGEINFODATA", "BONDING_INFO", "PRECHANGEUPPER",
			"CHANGELOWERSTATE", "UDP_TUNNEL_PUSH_INFO", "UDP_TUNNEL_DROP_INFO",
			"CHANGE_TX_QUEUE_LEN", "CVLAN_FILTER_PUSH_INFO", "CVLAN_FILTER_DROP_INFO",
			"SVLAN_FILTER_PUSH_INFO", "SVLAN_FILTER_DROP_INFO", "OFFLOAD_XSTATS_ENABLE",
			"OFFLOAD_XSTATS_DISABLE", "OFFLOAD_XSTATS_REPORT_USED",
			"OFFLOAD_XSTATS_REPORT_DELTA", "XDP_FEAT_CHANGE" } },
	{ header = "uapi/linux/bpf.h", prefix = "XDP_", module = "xdp.action",
		desc = "XDP verdicts (`enum xdp_action`), what an `xdp` callback returns.",
		include = { "ABORTED", "DROP", "PASS", "TX", "REDIRECT" } },
	{ header = "uapi/linux/bpf.h", prefix = "BPF_", module = "bpf",
		desc = "BPF map update flags.",
		include = { "ANY", "NOEXIST", "EXIST" } },
	{ header = "uapi/linux/bpf.h", prefix = "BPF_MAP_TYPE_", module = "bpf.map_type",
		desc = "BPF map types.",
		include = { "HASH", "ARRAY", "LRU_HASH", "QUEUE", "STACK" } },
	{ header = "uapi/linux/pkt_cls.h", prefix = "TC_ACT_", module = "tc.action",
		desc = "TC verdicts, what a `tc` callback returns.",
		exclude = { "TC_ACT_EXT_", "TC_ACT_VALUE_MAX" } },
	{ header = "uapi/linux/pkt_sched.h", prefix = "TC_H_", module = "tc.h",
		desc = "TC handles." },
	{ header = "linux/sched.h", prefix = "TASK_", module = "task",
		desc = "Task state flags." },
	{ header = "uapi/linux/errno.h", prefix = "E", module = "errno", strip = false,
		desc = "Error numbers, positive, keyed by the name `linux.errname` gives them." },
	{ header = "linux/sched/ext.h", prefix = "SCX_", module = "scx", optional = true,
		desc = "Extensible Scheduler (sched_ext) flags, from 6.12 on." },
	{ header = "linux/net.h", prefix = "SOCK_", module = "socket.sock",
		desc = "Socket types (SOCK_STREAM, SOCK_DGRAM, ...)." },
	{ header = "linux/socket.h", prefix = "AF_", module = "socket.af",
		desc = "Socket address families." },
	{ header = "linux/socket.h", prefix = "MSG_", module = "socket.msg",
		desc = "Message flags for send/recv." },
	{ header = "uapi/linux/in.h", prefix = "IPPROTO_", module = "socket.ipproto",
		desc = "IP-layer protocol numbers." },
	{ header = "linux/socket.h", prefix = "SOL_", module = "socket.sol",
		desc = "Socket option levels (SOL_*)." },
	{ header = "uapi/asm-generic/socket.h", prefix = "SO_", module = "socket.so",
		desc = "Socket-level option names (SO_*)." },
	{ header = "uapi/linux/time_types.h", module = "socket.layout", struct = "__kernel_sock_timeval",
		desc = "Socket option payload layouts.",
		as = "timeval",
		fields = { "tv_sec", "tv_usec" } },
	{ header = "uapi/linux/netfilter.h", prefix = "NFPROTO_", module = "nf.proto",
		desc = "Netfilter protocol families." },
	{ header = "uapi/linux/netfilter.h", prefix = "NF_INET_", module = "nf.inet",
		desc = "Netfilter hook positions in the INET family." },
	{ header = "uapi/linux/netfilter.h", prefix = "NF_NETDEV_", module = "nf.netdev",
		desc = "Netfilter hook positions in the NETDEV family." },
	{ header = "uapi/linux/netfilter_arp.h", prefix = "NF_ARP_", module = "nf.arp",
		desc = "Netfilter hook positions in the ARP family." },
	{ header = "uapi/linux/netfilter_ipv4.h", prefix = "NF_IP_PRI_", module = "nf.ip.pri",
		desc = "Netfilter hook priorities in the IP family." },
	{ header = "uapi/linux/netfilter_bridge.h", prefix = "NF_BR_", module = "nf.br",
		desc = "Netfilter hook positions in the BRIDGE family.",
		exclude = "NF_BR_PRI_" },
	{ header = "uapi/linux/netfilter_bridge.h", prefix = "NF_BR_PRI_", module = "nf.br.pri",
		desc = "Netfilter hook priorities in the BRIDGE family." },
	{ header = "uapi/linux/netfilter.h", prefix = "NF_", module = "nf.action",
		desc = "Netfilter hook verdicts.",
		include = { "DROP", "ACCEPT", "STOLEN", "QUEUE", "REPEAT", "STOP" } },
	{ header = "linux/skbuff.h", prefix = "SKB_DROP_REASON_", module = "dropreason",
		desc = "Socket buffer (skb) drop reasons, as `kfree_skb_reason()` receives them.",
		exclude = { "SKB_DROP_REASON_MAX", "SKB_DROP_REASON_SUBSYS_" } },
	{ header = "linux/skbuff.h", prefix = "SKB_", module = "dropreason",
		include = { "CONSUMED", "NOT_DROPPED_YET" } },
	{ header = "uapi/linux/netfilter/nf_conntrack_common.h", prefix = "IP_CT_", module = "nf.ct.info",
		desc = "Conntrack per-packet states (IS_REPLY is the reply-direction threshold, not a state).",
		exclude = { "IP_CT_DIR_", "IP_CT_NUMBER" } },
	{ header = "uapi/linux/netfilter/nf_conntrack_common.h", prefix = "IPS_", module = "nf.ct.status",
		desc = "Conntrack status flags (NAT_CLASH is the in-kernel meaning of the obsolete UNTRACKED bit).",
		include = { "EXPECTED", "SEEN_REPLY", "ASSURED", "CONFIRMED", "SRC_NAT", "DST_NAT",
			"SEQ_ADJUST", "SRC_NAT_DONE", "DST_NAT_DONE", "DYING", "FIXED_TIMEOUT",
			"TEMPLATE", "UNTRACKED", "NAT_CLASH", "HELPER", "OFFLOAD", "HW_OFFLOAD" } },
	{ header = "uapi/linux/netfilter/nf_conntrack_tuple_common.h", prefix = "IP_CT_DIR_", module = "nf.ct.dir",
		desc = "Conntrack tuple directions.",
		exclude = "IP_CT_DIR_MAX" },
	{ header = "uapi/linux/netfilter/nf_conntrack_tcp.h", prefix = "TCP_CONNTRACK_", module = "nf.ct.tcp",
		desc = "TCP conntrack states (SYN_SENT2 is the live name for the obsolete LISTEN).",
		include = { "NONE", "SYN_SENT", "SYN_RECV", "ESTABLISHED", "FIN_WAIT", "CLOSE_WAIT",
			"LAST_ACK", "TIME_WAIT", "CLOSE", "LISTEN", "SYN_SENT2" } },
	{ header = "uapi/linux/netlink.h", prefix = "NLMSG_", module = "netlink",
		desc = "Netlink wire alignment (NLMSG_ALIGNTO).",
		include = { "ALIGNTO" } },
	{ header = "uapi/linux/netlink.h", prefix = "NETLINK_", module = "netlink.proto",
		desc = "Netlink protocol numbers.",
		include = { "ROUTE", "GENERIC" } },
	{ header = "uapi/linux/netlink.h", prefix = "NLM_F_", module = "netlink.flag",
		desc = "Netlink message flags (NLM_F_*)." },
	{ header = "uapi/linux/netlink.h", prefix = "NLMSG_", module = "netlink.type",
		desc = "Special netlink message types.",
		include = { "NOOP", "ERROR", "DONE", "OVERRUN" } },
	{ header = "uapi/linux/netlink.h", module = "netlink.layout", struct = "nlmsghdr",
		desc = "Netlink header layouts.",
		fields = { "nlmsg_len", "nlmsg_type", "nlmsg_flags", "nlmsg_seq", "nlmsg_pid" } },
	{ header = "uapi/linux/netlink.h", module = "netlink.layout", struct = "nlattr",
		fields = { "nla_len", "nla_type" } },
	{ header = "uapi/linux/netlink.h", module = "netlink.layout", struct = "nlmsgerr",
		fields = { "error" } },
	{ header = "uapi/linux/genetlink.h", prefix = "GENL_ID_", module = "genl.id",
		desc = "Generic netlink reserved family ids (GENL_ID_*)." },
	{ header = "uapi/linux/genetlink.h", prefix = "CTRL_CMD_", module = "genl.ctrl.cmd",
		desc = "Generic netlink controller commands (CTRL_CMD_*)." },
	{ header = "uapi/linux/genetlink.h", prefix = "CTRL_ATTR_", module = "genl.ctrl.attr",
		desc = "Generic netlink controller attributes (CTRL_ATTR_*).",
		include = { "FAMILY_ID", "FAMILY_NAME", "VERSION", "HDRSIZE", "MAXATTR", "OPS", "MCAST_GROUPS",
			"POLICY", "OP_POLICY", "OP" } },
	{ header = "uapi/linux/genetlink.h", module = "genl.layout", struct = "genlmsghdr",
		desc = "Generic netlink header layout.",
		fields = { "cmd", "version", "reserved" } },
	{ header = "uapi/linux/rtnetlink.h", prefix = "RTM_", module = "rtnetlink.rtm",
		desc = "rtnetlink message types (RTM_*).",
		exclude = "RTM_F_" },
	{ header = "uapi/linux/rtnetlink.h", prefix = "RTA_", module = "rtnetlink.rta",
		desc = "rtnetlink route attribute types (RTA_*)." },
	{ header = "uapi/linux/rtnetlink.h", prefix = "RTN_", module = "rtnetlink.rtn",
		desc = "rtnetlink route types (RTN_*)." },
	{ header = "uapi/linux/rtnetlink.h", prefix = "RTPROT_", module = "rtnetlink.rtprot",
		desc = "rtnetlink route origins (RTPROT_*)." },
	{ header = "uapi/linux/rtnetlink.h", prefix = "RT_SCOPE_", module = "rtnetlink.scope",
		desc = "rtnetlink route scopes (RT_SCOPE_*)." },
	{ header = "uapi/linux/rtnetlink.h", prefix = "RT_TABLE_", module = "rtnetlink.table",
		desc = "rtnetlink routing table ids (RT_TABLE_*)." },
	{ header = "uapi/linux/if.h", prefix = "IFF_", module = "iff",
		desc = "Network device flags (IFF_*).",
		include = { "UP", "BROADCAST", "LOOPBACK", "POINTOPOINT", "RUNNING", "MULTICAST" } },
	{ header = "uapi/linux/if_link.h", prefix = "IFLA_", module = "rtnetlink.ifla",
		desc = "rtnetlink link attribute types (IFLA_*).",
		include = { "UNSPEC", "ADDRESS", "BROADCAST", "IFNAME", "MTU", "LINK",
			"QDISC", "STATS", "STATS64", "MASTER", "TXQLEN", "MAP", "WEIGHT",
			"OPERSTATE", "LINKMODE", "LINKINFO", "GROUP", "CARRIER",
			"CARRIER_CHANGES", "PROTO_DOWN", "MIN_MTU", "MAX_MTU",
			"PERM_ADDRESS", "PHYS_PORT_NAME", "PARENT_DEV_NAME" } },
	{ header = "uapi/linux/if_addr.h", prefix = "IFA_", module = "rtnetlink.ifa",
		desc = "rtnetlink address attribute types (IFA_*)." },
	{ header = "uapi/linux/fib_rules.h", prefix = "FRA_", module = "rtnetlink.fra",
		desc = "rtnetlink FIB rule attribute types (FRA_*)." },
	{ header = "uapi/linux/fib_rules.h", prefix = "FR_ACT_", module = "rtnetlink.fr_act",
		desc = "rtnetlink FIB rule actions (FR_ACT_*)." },
	{ header = "uapi/linux/rtnetlink.h", module = "rtnetlink.layout", struct = "rtmsg",
		desc = "rtnetlink message header layouts.",
		fields = { "rtm_family", "rtm_dst_len", "rtm_src_len", "rtm_tos", "rtm_table",
			"rtm_protocol", "rtm_scope", "rtm_type", "rtm_flags" } },
	{ header = "uapi/linux/if_link.h", module = "rtnetlink.layout", struct = "ifinfomsg",
		fields = { "ifi_family", "ifi_type", "ifi_index", "ifi_flags", "ifi_change" } },
	{ header = "uapi/linux/if_addr.h", module = "rtnetlink.layout", struct = "ifaddrmsg",
		fields = { "ifa_family", "ifa_prefixlen", "ifa_flags", "ifa_scope", "ifa_index" } },
	{ header = "uapi/linux/fib_rules.h", module = "rtnetlink.layout", struct = "fib_rule_hdr",
		fields = { "family", "dst_len", "src_len", "tos", "table", "action", "flags" } },
	{ header = "uapi/linux/nl80211.h", prefix = "NL80211_CMD_", module = "nl80211.cmd",
		desc = "nl80211 commands (NL80211_CMD_*).",
		include = { "GET_WIPHY", "NEW_WIPHY", "GET_INTERFACE", "SET_INTERFACE",
			"NEW_INTERFACE", "DEL_INTERFACE", "START_AP", "STOP_AP",
			"GET_STATION", "NEW_STATION", "DEL_STATION", "SET_STATION",
			"GET_SCAN", "TRIGGER_SCAN", "NEW_SCAN_RESULTS" } },
	{ header = "uapi/linux/nl80211.h", prefix = "NL80211_ATTR_", module = "nl80211.attr",
		desc = "nl80211 attributes (NL80211_ATTR_*).",
		include = { "WIPHY", "WIPHY_NAME", "WIPHY_FREQ", "IFINDEX", "IFNAME", "IFTYPE", "MAC",
			"SSID", "BEACON_INTERVAL", "DTIM_PERIOD", "BEACON_HEAD", "BEACON_TAIL",
			"STA_AID", "STA_LISTEN_INTERVAL", "STA_SUPPORTED_RATES", "STA_FLAGS2",
			"GENERATION", "WDEV", "STA_INFO", "SCAN_SSIDS", "BSS" } },
	{ header = "uapi/linux/nl80211.h", prefix = "NL80211_STA_FLAG_", module = "nl80211.sta_flag",
		desc = "nl80211 station flags (NL80211_STA_FLAG_*), bit positions for STA_FLAGS2.",
		include = { "AUTHORIZED", "SHORT_PREAMBLE", "WME", "MFP", "AUTHENTICATED",
			"TDLS_PEER", "ASSOCIATED" } },
	{ header = "uapi/linux/nl80211.h", prefix = "NL80211_IFTYPE_", module = "nl80211.iftype",
		desc = "nl80211 interface types (NL80211_IFTYPE_*).",
		include = { "STATION", "AP", "MONITOR", "ADHOC", "AP_VLAN", "MESH_POINT" } },
	{ header = "asm/unistd.h", prefix = "__NR_", module = "syscall.numbers",
		desc = "System call numbers (`__NR_*`) for the build arch.",
		exclude = { "__NR_arch_specific_syscall", "__NR_compat_", "__NR_syscalls",
			"__NR_x32_", "__NR_ia32_" } },
}

