--
-- SPDX-FileCopyrightText: (c) 2026 Ring Zero Desenvolvimento de Software LTDA
-- SPDX-License-Identifier: MIT OR GPL-2.0-only
--
-- Input for autogen.lua. Each entry produces one autogen/linux/<module>.lua
-- with integer constants matching `prefix` stripped from the Lua table key.
--
-- @field header path relative to $(KBUILD)/include
-- @field prefix constant prefix
-- @field module name of the resulting Lua module
-- @field desc   short LDoc description used by autogen/ldoc.lua

return {
	{ header = "uapi/linux/if_ether.h",         prefix = "ETH_P_",     module = "eth",
		desc = "Ethernet protocol IDs." },
	{ header = "linux/stat.h",                  prefix = "S_",         module = "stat",
		desc = "File mode bits." },
	{ header = "uapi/linux/signal.h",           prefix = "SIG",        module = "signal",
		desc = "POSIX signal numbers." },
	{ header = "linux/notifier.h",              prefix = "NOTIFY_",    module = "notify",
		desc = "Return codes for kernel notifier chains." },
	{ header = "linux/notifier.h",              prefix = "KBD_",       module = "kbd",
		desc = "Keyboard notifier event types." },
	{ header = "linux/vt.h",                    prefix = "VT_",        module = "vt",
		desc = "Virtual terminal notifier event types." },
	{ header = "linux/netdevice.h",             prefix = "NETDEV_",    module = "netdev",
		desc = "Network device notifier event types." },
	{ header = "uapi/linux/bpf.h",              prefix = "XDP_",       module = "xdp",
		desc = "XDP verdicts and flags." },
	{ header = "linux/sched.h",                 prefix = "TASK_",      module = "task",
		desc = "Task state flags." },
	{ header = "linux/net.h",                   prefix = "SOCK_",      module = "socket.sock",
		desc = "Socket types (SOCK_STREAM, SOCK_DGRAM, ...)." },
	{ header = "linux/socket.h",                prefix = "AF_",        module = "socket.af",
		desc = "Socket address families." },
	{ header = "linux/socket.h",                prefix = "MSG_",       module = "socket.msg",
		desc = "Message flags for send/recv." },
	{ header = "uapi/linux/in.h",               prefix = "IPPROTO_",   module = "socket.ipproto",
		desc = "IP-layer protocol numbers." },
	{ header = "uapi/linux/netfilter.h",        prefix = "NFPROTO_",   module = "nf.proto",
		desc = "Netfilter protocol families." },
	{ header = "uapi/linux/netfilter.h",        prefix = "NF_INET_",   module = "nf.inet",
		desc = "Netfilter hook positions in the INET family." },
	{ header = "uapi/linux/netfilter.h",        prefix = "NF_NETDEV_", module = "nf.netdev",
		desc = "Netfilter hook positions in the NETDEV family." },
	{ header = "uapi/linux/netfilter_arp.h",    prefix = "NF_ARP_",    module = "nf.arp",
		desc = "Netfilter hook positions in the ARP family." },
	{ header = "uapi/linux/netfilter_ipv4.h",   prefix = "NF_IP_PRI_", module = "nf.ip.pri",
		desc = "Netfilter hook priorities in the IP family." },
	{ header = "uapi/linux/netfilter_bridge.h", prefix = "NF_BR_",     module = "nf.br",
		desc = "Netfilter hook positions in the BRIDGE family.",
		exclude = "NF_BR_PRI_" },
	{ header = "uapi/linux/netfilter_bridge.h", prefix = "NF_BR_PRI_", module = "nf.br.pri",
		desc = "Netfilter hook priorities in the BRIDGE family." },
	{ header = "uapi/linux/netfilter.h",        prefix = "NF_",        module = "nf.action",
		desc = "Netfilter hook verdicts.",
		include = { "DROP", "ACCEPT", "STOLEN", "QUEUE", "REPEAT", "STOP" } },
	{ header = "uapi/linux/netlink.h",          prefix = "NETLINK_",   module = "netlink.proto",
		desc = "Netlink protocol numbers.",
		include = { "ROUTE", "GENERIC" } },
	{ header = "uapi/linux/netlink.h",          prefix = "NLM_F_",     module = "netlink.flag",
		desc = "Netlink message flags (NLM_F_*)." },
	{ header = "uapi/linux/netlink.h",          prefix = "NLMSG_",     module = "netlink.type",
		desc = "Special netlink message types.",
		include = { "NOOP", "ERROR", "DONE", "OVERRUN" } },
	{ header = "uapi/linux/rtnetlink.h",        prefix = "RTM_",       module = "rtnetlink.rtm",
		desc = "rtnetlink message types (RTM_*).",
		exclude = "RTM_F_" },
	{ header = "uapi/linux/rtnetlink.h",        prefix = "RTA_",       module = "rtnetlink.rta",
		desc = "rtnetlink route attribute types (RTA_*)." },
	{ header = "uapi/linux/rtnetlink.h",        prefix = "RTN_",       module = "rtnetlink.rtn",
		desc = "rtnetlink route types (RTN_*)." },
	{ header = "uapi/linux/rtnetlink.h",        prefix = "RTPROT_",    module = "rtnetlink.rtprot",
		desc = "rtnetlink route origins (RTPROT_*)." },
	{ header = "uapi/linux/rtnetlink.h",        prefix = "RT_SCOPE_",  module = "rtnetlink.scope",
		desc = "rtnetlink route scopes (RT_SCOPE_*)." },
	{ header = "uapi/linux/rtnetlink.h",        prefix = "RT_TABLE_",  module = "rtnetlink.table",
		desc = "rtnetlink routing table ids (RT_TABLE_*)." },
	{ header = "uapi/linux/if_link.h",          prefix = "IFLA_",      module = "rtnetlink.ifla",
		desc = "rtnetlink link attribute types (IFLA_*).",
		include = { "UNSPEC", "ADDRESS", "BROADCAST", "IFNAME", "MTU", "LINK",
			"QDISC", "STATS", "STATS64", "MASTER", "TXQLEN", "MAP", "WEIGHT",
			"OPERSTATE", "LINKMODE", "LINKINFO", "GROUP", "CARRIER",
			"CARRIER_CHANGES", "PROTO_DOWN", "MIN_MTU", "MAX_MTU",
			"PERM_ADDRESS", "PHYS_PORT_NAME", "PARENT_DEV_NAME" } },
	{ header = "uapi/linux/if_addr.h",          prefix = "IFA_",       module = "rtnetlink.ifa",
		desc = "rtnetlink address attribute types (IFA_*)." },
	{ header = "asm/unistd.h",                  prefix = "__NR_",      module = "syscall.numbers",
		desc = "System call numbers (`__NR_*`) for the build arch.",
		exclude = { "__NR_arch_specific_syscall", "__NR_compat_", "__NR_syscalls",
			"__NR_x32_", "__NR_ia32_" } },
}

