#
# klibc files for ppc
#

klib-y := setjmp.o syscall.o

klib-y += ../../libgcc/__divdi3.o     ../../libgcc/__moddi3.o
klib-y += ../../libgcc/__udivdi3.o    ../../libgcc/__umoddi3.o
klib-y += ../../libgcc/__udivmoddi4.o

always  := crt0.o
targets := crt0.o
