#!/usr/bin/lua
--
-- Copyright (c) 2023 ring-0 Ltda.
--
-- Permission is hereby granted, free of charge, to any person obtaining
-- a copy of this software and associated documentation files (the
-- "Software"), to deal in the Software without restriction, including
-- without limitation the rights to use, copy, modify, merge, publish,
-- distribute, sublicense, and/or sell copies of the Software, and to
-- permit persons to whom the Software is furnished to do so, subject to
-- the following conditions:
--
-- The above copyright notice and this permission notice shall be
-- included in all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
-- EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
-- IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
-- CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
-- TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
-- SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
--

local lunatik = {
	copyright = "Copyright (C) 2023 ring-0 Ltda.",
	device = "/dev/lunatik",
	modules = {"lunatik", "luadevice", "lualinux", "luanotifier", "luasocket", "luarcu",
		"luathread", "luafib", "luadata", "luaprobe", "luasyscall", "lunatik_run"}
}

function lunatik.prompt()
	io.write("> ")
	io.flush()
end

function lunatik.open(mode)
	return io.open(lunatik.device, mode)
end

function lunatik.probe()
	local prober <close> = lunatik.open("r")
	return prober and true or false
end

function lunatik.loadstring(chunk)
	local loader <close> = lunatik.open("w")
	loader:write(chunk)
end

function lunatik.result()
	local reader <close> = lunatik.open("r")
	return reader:read("a")
end

function lunatik.dostring(chunk)
	lunatik.loadstring(chunk)
	return lunatik.result()
end

function lunatik.usage()
	print("usage: lunatik [load|unload|reload|status|list] [run|spawn|stop <script>]")
	os.exit(false)
end

function lunatik.sh(command, module, loaded)
	local isloaded = loaded and "&&" or "||"
	os.execute(string.format("MODULE=%s;grep -wq $MODULE /proc/modules %s%s", module, isloaded, command))
end

lunatik.commands = {
	['load'] = function ()
		for _, module in ipairs(lunatik.modules) do
			local path = "/lib/modules/`uname -r`/lunatik"
			lunatik.sh("modprobe -s $MODULE || insmod " .. path .. "/$MODULE.ko", module)
		end
	end,
	['unload'] = function ()
		if lunatik.probe() then
			lunatik.dostring("lunatik.driver:shutdown()")
		end

		local first = #lunatik.modules
		for i = first, 1, -1 do
			local module = lunatik.modules[i]
			lunatik.sh("rmmod $MODULE", module, true)
		end
	end,
	['reload'] = function()
		local commands = lunatik.commands
		commands.unload()
		commands.load()
	end,
	['status'] = function ()
		for _, module in ipairs(lunatik.modules) do
			lunatik.sh("echo $MODULE is loaded || echo $MODULE is not loaded", module, true)
		end
	end
}

local command = lunatik.commands[arg[1]]
if command then
	command()
	os.exit()
end

if not lunatik.probe() then
	lunatik.commands.load()
end

local version = lunatik.dostring("return _LUNATIK_VERSION")
lunatik.copyright = version .. "  " .. lunatik.copyright

local function set(t)
	local s = {}
	for _, key in ipairs(t) do s[key] = true end
	return s
end

local tokens = set{"run", "spawn", "stop", "list"}

if #arg >= 1 then
	local token = arg[1]
	if tokens[token] then
		local ret = token == "list" and "return" or ""
		local chunk = string.format("%s lunatik.driver:%s('%s')", ret, token, arg[2])
		print(lunatik.dostring(chunk))
	else
		lunatik.usage()
	end
	os.exit()
end

print(lunatik.copyright)
lunatik.prompt()
for chunk in io.lines() do
	print(lunatik.dostring(chunk))
	lunatik.prompt()
end

