window.LUNATIK_SEARCH = [
["bpf","modules/bpf.html","Module · Lua interface to eBPF."],
["bpf_hash:close ()","modules/bpf.html#bpf_hash:close","bpf · Releases the map reference."],
["bpf_hash:delete (key)","modules/bpf.html#bpf_hash:delete","bpf · Deletes a key from the map."],
["bpf_hash:info ()","modules/bpf.html#bpf_hash:info","bpf · Returns the map properties."],
["bpf_hash:lookup (key)","modules/bpf.html#bpf_hash:lookup","bpf · Looks up a key from the map."],
["bpf_hash:next ([key])","modules/bpf.html#bpf_hash:next","bpf · Returns the next key in the map."],
["bpf_hash:remove (key)","modules/bpf.html#bpf_hash:remove","bpf · Looks up and deletes a key from the map."],
["bpf_hash:update (key, value[, flags=BPF_ANY])","modules/bpf.html#bpf_hash:update","bpf · Updates a key in the map."],
["bpf_queue:peek ()","modules/bpf.html#bpf_queue:peek","bpf · Peeks at the next value of the map without removing it."],
["bpf_queue:pop ()","modules/bpf.html#bpf_queue:pop","bpf · Pops (removes and returns) the next value from the map."],
["bpf_queue:push (value[, flags=BPF_ANY])","modules/bpf.html#bpf_queue:push","bpf · Pushes a value onto the map."],
["array (path)","modules/bpf.html#array","bpf · Opens an array map from a pinned bpffs path."],
["hash (path)","modules/bpf.html#hash","bpf · Opens a hash map from a pinned bpffs path."],
["lru_hash (path)","modules/bpf.html#lru_hash","bpf · Opens an LRU hash map from a pinned bpffs path."],
["queue (path)","modules/bpf.html#queue","bpf · Opens a queue (FIFO) map from a pinned bpffs path."],
["stack (path)","modules/bpf.html#stack","bpf · Opens a stack (LIFO) map from a pinned bpffs path."],
["bpf.map","modules/bpf.map.html","Module · High-level view over pinned eBPF maps."],
["array (pathname, keyspec, valuespec)","modules/bpf.map.html#array","bpf.map · Opens a pinned array map as a table."],
["close (proxy)","modules/bpf.map.html#close","bpf.map · Releases the map reference."],
["hash (pathname, keyspec, valuespec)","modules/bpf.map.html#hash","bpf.map · Opens a pinned hash map as a table."],
["info (proxy)","modules/bpf.map.html#info","bpf.map · Returns the map properties, as bpf map info."],
["lru_hash (pathname, keyspec, valuespec)","modules/bpf.map.html#lru_hash","bpf.map · Opens a pinned LRU hash map as a table."],
["queue (pathname, valuespec)","modules/bpf.map.html#queue","bpf.map · Opens a pinned queue map (FIFO)."],
["stack (pathname, valuespec)","modules/bpf.map.html#stack","bpf.map · Opens a pinned stack map (LIFO)."],
["map_queue:close ()","modules/bpf.map.html#map_queue:close","bpf.map · Releases the map reference."],
["map_queue:info ()","modules/bpf.map.html#map_queue:info","bpf.map · Returns the map properties, as bpf map info."],
["map_queue:peek ()","modules/bpf.map.html#map_queue:peek","bpf.map · Returns the next value, leaving it in the map."],
["map_queue:pop ()","modules/bpf.map.html#map_queue:pop","bpf.map · Removes and returns the next value."],
["map_queue:push (value)","modules/bpf.map.html#map_queue:push","bpf.map · Inserts a value."],
["byteorder","modules/byteorder.html","Module · Byte Order Conversion"],
["be16toh (num16)","modules/byteorder.html#be16toh","byteorder · Converts a 16-bit integer from big-endian byte order to host byte order."],
["be32toh (num32)","modules/byteorder.html#be32toh","byteorder · Converts a 32-bit integer from big-endian byte order to host byte order."],
["be64toh (num64)","modules/byteorder.html#be64toh","byteorder · Converts a 64-bit integer from big-endian byte order to host byte order."],
["htobe16 (num16)","modules/byteorder.html#htobe16","byteorder · Converts a 16-bit integer from host byte order to big-endian byte order."],
["htobe32 (num32)","modules/byteorder.html#htobe32","byteorder · Converts a 32-bit integer from host byte order to big-endian byte order."],
["htobe64 (num64)","modules/byteorder.html#htobe64","byteorder · Converts a 64-bit integer from host byte order to big-endian byte order."],
["htole16 (num16)","modules/byteorder.html#htole16","byteorder · Converts a 16-bit integer from host byte order to little-endian byte order."],
["htole32 (num32)","modules/byteorder.html#htole32","byteorder · Converts a 32-bit integer from host byte order to little-endian byte order."],
["htole64 (num64)","modules/byteorder.html#htole64","byteorder · Converts a 64-bit integer from host byte order to little-endian byte order."],
["hton16 (num16)","modules/byteorder.html#hton16","byteorder · Converts a 16-bit integer from host byte order to network (big-endian) byte order."],
["hton32 (num32)","modules/byteorder.html#hton32","byteorder · Converts a 32-bit integer from host byte order to network (big-endian) byte order."],
["hton64 (num64)","modules/byteorder.html#hton64","byteorder · Converts a 64-bit integer from host byte order to network (big-endian) byte order."],
["le16toh (num16)","modules/byteorder.html#le16toh","byteorder · Converts a 16-bit integer from little-endian byte order to host byte order."],
["le32toh (num32)","modules/byteorder.html#le32toh","byteorder · Converts a 32-bit integer from little-endian byte order to host byte order."],
["le64toh (num64)","modules/byteorder.html#le64toh","byteorder · Converts a 64-bit integer from little-endian byte order to host byte order."],
["ntoh16 (num16)","modules/byteorder.html#ntoh16","byteorder · Converts a 16-bit integer from network (big-endian) byte order to host byte order."],
["ntoh32 (num32)","modules/byteorder.html#ntoh32","byteorder · Converts a 32-bit integer from network (big-endian) byte order to host byte order."],
["ntoh64 (num64)","modules/byteorder.html#ntoh64","byteorder · Converts a 64-bit integer from network (big-endian) byte order to host byte order."],
["class","modules/class.html","Module · Minimal class helper for the OOP-style modules (e.g."],
["completion","modules/completion.html","Module · Lua bindings for kernel completion mechanisms."],
["completion:complete ()","modules/completion.html#completion:complete","completion · Signals a completion."],
["completion:wait ([timeout])","modules/completion.html#completion:wait","completion · Waits for a completion to be signaled."],
["new ()","modules/completion.html#new","completion · Creates a new kernel completion object."],
["cpu","modules/cpu.html","Module · Lua interface to Linux CPU abstractions."],
["foreach_online (callback)","modules/cpu.html#foreach_online","cpu · Calls a function for each online CPU."],
["foreach_possible (callback)","modules/cpu.html#foreach_possible","cpu · Calls a function for each possible CPU."],
["foreach_present (callback)","modules/cpu.html#foreach_present","cpu · Calls a function for each present CPU."],
["num_online ()","modules/cpu.html#num_online","cpu · "],
["num_possible ()","modules/cpu.html#num_possible","cpu · "],
["num_present ()","modules/cpu.html#num_present","cpu · "],
["stats (cpu)","modules/cpu.html#stats","cpu · Returns CPU time statistics for a given CPU."],
["crypto","modules/crypto.html","Module · Lua interface to the Linux Crypto API."],
["darken","modules/darken.html","Module · Encrypted Lua script execution using AES-256-CTR."],
["run (ciphertext, iv, key)","modules/darken.html#run","darken · Decrypts and executes an encrypted Lua script."],
["data","modules/data.html","Module · Direct memory access and manipulation."],
["data:__len ()","modules/data.html#data:__len","data · "],
["data:__tostring ()","modules/data.html#data:__tostring","data · "],
["data:checksum ([offset[, length]])","modules/data.html#data:checksum","data · "],
["data:getbyte (offset)","modules/data.html#data:getbyte","data · "],
["data:getint16 (offset)","modules/data.html#data:getint16","data · "],
["data:getint32 (offset)","modules/data.html#data:getint32","data · "],
["data:getint64 (offset)","modules/data.html#data:getint64","data · "],
["data:getint8 (offset)","modules/data.html#data:getint8","data · "],
["data:getnumber (offset)","modules/data.html#data:getnumber","data · "],
["data:getstring (offset[, length])","modules/data.html#data:getstring","data · "],
["data:getuint16 (offset)","modules/data.html#data:getuint16","data · "],
["data:getuint32 (offset)","modules/data.html#data:getuint32","data · "],
["data:getuint8 (offset)","modules/data.html#data:getuint8","data · "],
["data:resize (new_size)","modules/data.html#data:resize","data · Resizes the buffer; the bytes it keeps survive and the bytes a growth adds read as zeros."],
["data:setbyte (offset, value)","modules/data.html#data:setbyte","data · "],
["data:setint16 (offset, value)","modules/data.html#data:setint16","data · "],
["data:setint32 (offset, value)","modules/data.html#data:setint32","data · "],
["data:setint64 (offset, value)","modules/data.html#data:setint64","data · "],
["data:setint8 (offset, value)","modules/data.html#data:setint8","data · "],
["data:setnumber (offset, value)","modules/data.html#data:setnumber","data · "],
["data:setstring (offset, s)","modules/data.html#data:setstring","data · "],
["data:setuint16 (offset, value)","modules/data.html#data:setuint16","data · "],
["data:setuint32 (offset, value)","modules/data.html#data:setuint32","data · "],
["data:setuint8 (offset, value)","modules/data.html#data:setuint8","data · "],
["new (size[, mode])","modules/data.html#new","data · Allocates a buffer of size bytes, zeroed."],
["device","modules/device.html","Module · Low-level Lua interface for creating Linux character device drivers."],
["device:new (driver)","modules/device.html#device:new","device · Creates and installs a new character device driver in the system."],
["device:stop ()","modules/device.html#device:stop","device · Stops a character device driver and removes it from the system."],
["fifo","modules/fifo.html","Module · kfifo (kernel FIFO) implementation."],
["pop (size)","modules/fifo.html#pop","fifo · Pops data from the FIFO."],
["push (data)","modules/fifo.html#push","fifo · Pushes data into the FIFO."],
["fifo:close ()","modules/fifo.html#fifo:close","fifo · Closes and releases the FIFO object."],
["new (size)","modules/fifo.html#new","fifo · Creates a new kernel FIFO (kfifo) object."],
["fsnotify","modules/fsnotify.html","Module · Filesystem notification."],
["fsnotify_watch:find (path[, kind])","modules/fsnotify.html#fsnotify_watch:find","fsnotify · Finds the mark this watch placed on an object."],
["fsnotify_watch:mark (path, mask[, kind])","modules/fsnotify.html#fsnotify_watch:mark","fsnotify · Places a mark on a filesystem object."],
["fsnotify_watch:stop ()","modules/fsnotify.html#fsnotify_watch:stop","fsnotify · Stops the watch."],
["fsnotify_mark:ignore ([mask])","modules/fsnotify.html#fsnotify_mark:ignore","fsnotify · Reads the mark's ignore mask, or sets it."],
["fsnotify_mark:mask ([mask])","modules/fsnotify.html#fsnotify_mark:mask","fsnotify · Reads the mark's event mask, or sets it."],
["fsnotify_mark:remove ()","modules/fsnotify.html#fsnotify_mark:remove","fsnotify · Removes the mark."],
["fsnotify_event:dir ()","modules/fsnotify.html#fsnotify_event:dir","fsnotify · Returns the inode number of the directory the entry the event names lives in."],
["fsnotify_event:ino ()","modules/fsnotify.html#fsnotify_event:ino","fsnotify · Returns the inode number of the object the event is about."],
["fsnotify_event:isdir ()","modules/fsnotify.html#fsnotify_event:isdir","fsnotify · Tells whether the event is about a directory."],
["fsnotify_event:name ()","modules/fsnotify.html#fsnotify_event:name","fsnotify · Returns the directory entry name the event is about."],
["fsnotify_event:path ()","modules/fsnotify.html#fsnotify_event:path","fsnotify · Returns the full path of the object the event is about."],
["fsnotify_event:pid ()","modules/fsnotify.html#fsnotify_event:pid","fsnotify · Returns the pid of the task performing the access."],
["action","modules/fsnotify.html#action","fsnotify · What a callback answers a permission event with."],
["watch (callback)","modules/fsnotify.html#watch","fsnotify · Creates a watch."],
["hid","modules/hid.html","Module · Lua interface to the Linux HID subsystem."],
["hid_driver:register (opts)","modules/hid.html#hid_driver:register","hid · Registers a new HID driver."],
["lighten","modules/lighten.html","Module · Encrypted Lua script support (AES-256-CTR)."],
["run (ct, iv)","modules/lighten.html#run","lighten · Decrypts and executes an encrypted Lua script."],
["linux.bpf","modules/linux.bpf.html","Module · Linux kernel constants exposed under linux.bpf."],
["constants","modules/linux.bpf.html#constants","linux.bpf · BPF map types and update flags."],
["linux.dropreason","modules/linux.dropreason.html","Module · Linux kernel constants exposed under linux.dropreason."],
["constants","modules/linux.dropreason.html#constants","linux.dropreason · Socket buffer (skb) drop reasons, as kfree_skb_reason() receives them."],
["linux.eth","modules/linux.eth.html","Module · Linux kernel constants exposed under linux.eth."],
["constants","modules/linux.eth.html#constants","linux.eth · Ethernet protocol IDs."],
["linux.fs","modules/linux.fs.html","Module · Linux kernel constants exposed under linux.fs."],
["constants","modules/linux.fs.html#constants","linux.fs · Filesystem notification event masks and flags."],
["linux.genl","modules/linux.genl.html","Module · Linux kernel constants exposed under linux.genl."],
["attr","modules/linux.genl.html#attr","linux.genl · Generic netlink controller attributes (CTRL_ATTR_*)."],
["cmd","modules/linux.genl.html#cmd","linux.genl · Generic netlink controller commands (CTRL_CMD_*)."],
["id","modules/linux.genl.html#id","linux.genl · Generic netlink reserved family ids (GENL_ID_*)."],
["layout","modules/linux.genl.html#layout","linux.genl · Generic netlink header layout."],
["linux","modules/linux.html","Module · Various Linux kernel facilities."],
["difftime (t2, t1)","modules/linux.html#difftime","linux · Calculates the difference between two timestamps."],
["errname (err)","modules/linux.html#errname","linux · Returns the symbolic name of a kernel error number."],
["ifaddr (ifindex)","modules/linux.html#ifaddr","linux · Gets the HW address for the network interface index."],
["ifindex (interface_name)","modules/linux.html#ifindex","linux · Gets the interface index for a network device name."],
["lookup (symbol_name)","modules/linux.html#lookup","linux · Looks up a kernel symbol by name."],
["netns ([pid])","modules/linux.html#netns","linux · Gets the inode number that identifies a network namespace, the one /proc/<pid>/ns/net links to and lsns prints."],
["numcpus ()","modules/linux.html#numcpus","linux · Returns the number of possible CPU ids."],
["random ([m[, n]])","modules/linux.html#random","linux · Generates pseudo-random integers."],
["schedule ([timeout[, state]])","modules/linux.html#schedule","linux · Puts the current task to sleep."],
["time ()","modules/linux.html#time","linux · Gets the current real time."],
["tracing ([enable])","modules/linux.html#tracing","linux · Controls kernel tracing."],
["linux.kbd","modules/linux.kbd.html","Module · Linux kernel constants exposed under linux.kbd."],
["constants","modules/linux.kbd.html#constants","linux.kbd · Keyboard notifier event types."],
["linux.netdev","modules/linux.netdev.html","Module · Linux kernel constants exposed under linux.netdev."],
["constants","modules/linux.netdev.html#constants","linux.netdev · Network device notifier event types."],
["linux.netlink","modules/linux.netlink.html","Module · Linux kernel constants exposed under linux.netlink."],
["constants","modules/linux.netlink.html#constants","linux.netlink · Netlink wire alignment (NLMSG_ALIGNTO)."],
["flag","modules/linux.netlink.html#flag","linux.netlink · Netlink message flags (NLM_F_*)."],
["layout","modules/linux.netlink.html#layout","linux.netlink · Netlink header layouts."],
["proto","modules/linux.netlink.html#proto","linux.netlink · Netlink protocol numbers."],
["type","modules/linux.netlink.html#type","linux.netlink · Special netlink message types."],
["linux.nf","modules/linux.nf.html","Module · Linux kernel constants exposed under linux.nf."],
["action","modules/linux.nf.html#action","linux.nf · Netfilter hook verdicts."],
["arp","modules/linux.nf.html#arp","linux.nf · Netfilter hook positions in the ARP family."],
["br","modules/linux.nf.html#br","linux.nf · Netfilter hook positions in the BRIDGE family."],
["br.pri","modules/linux.nf.html#br.pri","linux.nf · Netfilter hook priorities in the BRIDGE family."],
["ct.dir","modules/linux.nf.html#ct.dir","linux.nf · Conntrack tuple directions."],
["ct.info","modules/linux.nf.html#ct.info","linux.nf · Conntrack per-packet states (IS_REPLY is the reply-direction threshold, not a state)."],
["ct.status","modules/linux.nf.html#ct.status","linux.nf · Conntrack status flags (NAT_CLASH is the in-kernel meaning of the obsolete UNTRACKED bit)."],
["ct.tcp","modules/linux.nf.html#ct.tcp","linux.nf · TCP conntrack states (SYN_SENT2 is the live name for the obsolete LISTEN)."],
["inet","modules/linux.nf.html#inet","linux.nf · Netfilter hook positions in the INET family."],
["ip.pri","modules/linux.nf.html#ip.pri","linux.nf · Netfilter hook priorities in the IP family."],
["netdev","modules/linux.nf.html#netdev","linux.nf · Netfilter hook positions in the NETDEV family."],
["proto","modules/linux.nf.html#proto","linux.nf · Netfilter protocol families."],
["linux.nl80211","modules/linux.nl80211.html","Module · Linux kernel constants exposed under linux.nl80211."],
["attr","modules/linux.nl80211.html#attr","linux.nl80211 · nl80211 attributes (NL80211_ATTR_*)."],
["cmd","modules/linux.nl80211.html#cmd","linux.nl80211 · nl80211 commands (NL80211_CMD_*)."],
["iftype","modules/linux.nl80211.html#iftype","linux.nl80211 · nl80211 interface types (NL80211_IFTYPE_*)."],
["staflag","modules/linux.nl80211.html#staflag","linux.nl80211 · nl80211 station flags (NL80211_STA_FLAG_*), bit positions for STA_FLAGS2."],
["linux.notify","modules/linux.notify.html","Module · Linux kernel constants exposed under linux.notify."],
["constants","modules/linux.notify.html#constants","linux.notify · Return codes for kernel notifier chains."],
["linux.rtnetlink","modules/linux.rtnetlink.html","Module · Linux kernel constants exposed under linux.rtnetlink."],
["fr_act","modules/linux.rtnetlink.html#fr_act","linux.rtnetlink · rtnetlink FIB rule actions (FR_ACT_*)."],
["fra","modules/linux.rtnetlink.html#fra","linux.rtnetlink · rtnetlink FIB rule attribute types (FRA_*)."],
["ifa","modules/linux.rtnetlink.html#ifa","linux.rtnetlink · rtnetlink address attribute types (IFA_*)."],
["iff","modules/linux.rtnetlink.html#iff","linux.rtnetlink · Network device flags (IFF_*)."],
["ifla","modules/linux.rtnetlink.html#ifla","linux.rtnetlink · rtnetlink link attribute types (IFLA_*)."],
["layout","modules/linux.rtnetlink.html#layout","linux.rtnetlink · rtnetlink message header layouts."],
["rta","modules/linux.rtnetlink.html#rta","linux.rtnetlink · rtnetlink route attribute types (RTA_*)."],
["rtm","modules/linux.rtnetlink.html#rtm","linux.rtnetlink · rtnetlink message types (RTM_*)."],
["rtn","modules/linux.rtnetlink.html#rtn","linux.rtnetlink · rtnetlink route types (RTN_*)."],
["rtprot","modules/linux.rtnetlink.html#rtprot","linux.rtnetlink · rtnetlink route origins (RTPROT_*)."],
["scope","modules/linux.rtnetlink.html#scope","linux.rtnetlink · rtnetlink route scopes (RT_SCOPE_*)."],
["table","modules/linux.rtnetlink.html#table","linux.rtnetlink · rtnetlink routing table ids (RT_TABLE_*)."],
["linux.scx","modules/linux.scx.html","Module · Linux kernel constants exposed under linux.scx."],
["constants","modules/linux.scx.html#constants","linux.scx · Extensible Scheduler flags."],
["linux.signal","modules/linux.signal.html","Module · Linux kernel constants exposed under linux.signal."],
["constants","modules/linux.signal.html#constants","linux.signal · POSIX signal numbers."],
["linux.socket","modules/linux.socket.html","Module · Linux kernel constants exposed under linux.socket."],
["af","modules/linux.socket.html#af","linux.socket · Socket address families."],
["ipproto","modules/linux.socket.html#ipproto","linux.socket · IP-layer protocol numbers."],
["layout","modules/linux.socket.html#layout","linux.socket · Socket option payload layouts."],
["msg","modules/linux.socket.html#msg","linux.socket · Message flags for send/recv."],
["so","modules/linux.socket.html#so","linux.socket · Socket-level option names (SO_*)."],
["sock","modules/linux.socket.html#sock","linux.socket · Socket types (SOCK_STREAM, SOCK_DGRAM, )."],
["sol","modules/linux.socket.html#sol","linux.socket · Socket option levels (SOL_*)."],
["linux.stat","modules/linux.stat.html","Module · Linux kernel constants exposed under linux.stat."],
["constants","modules/linux.stat.html#constants","linux.stat · File mode bits."],
["linux.syscall","modules/linux.syscall.html","Module · Linux kernel constants exposed under linux.syscall."],
["numbers","modules/linux.syscall.html#numbers","linux.syscall · System call numbers (__NR_*) for the build arch."],
["linux.task","modules/linux.task.html","Module · Linux kernel constants exposed under linux.task."],
["constants","modules/linux.task.html#constants","linux.task · Task state flags."],
["linux.tc","modules/linux.tc.html","Module · Linux kernel constants exposed under linux.tc."],
["constants","modules/linux.tc.html#constants","linux.tc · TC verdicts and flags."],
["linux.vt","modules/linux.vt.html","Module · Linux kernel constants exposed under linux.vt."],
["constants","modules/linux.vt.html#constants","linux.vt · Virtual terminal notifier event types."],
["linux.xdp","modules/linux.xdp.html","Module · Linux kernel constants exposed under linux.xdp."],
["constants","modules/linux.xdp.html#constants","linux.xdp · XDP verdicts and flags."],
["lunatik","modules/lunatik.html","Module · Manages Lunatik runtimes — isolated Lua states running in the kernel."],
["_ENV","modules/lunatik.html#_ENV","lunatik · Shared global environment; scripts exchange objects (e.g."],
["cpu ()","modules/lunatik.html#cpu","lunatik · Returns the CPU id a percpu runtime serves."],
["percpu (script[, context=\"process\"])","modules/lunatik.html#percpu","lunatik · Creates one runtime per CPU id, each loading the given script in the calling context."],
["runtime (script[, context=\"process\"])","modules/lunatik.html#runtime","lunatik · Creates a new Lunatik runtime executing the given script."],
["runtime:resume (...)","modules/lunatik.html#runtime:resume","lunatik · Resumes a yielded runtime, analogous to coroutine.resume."],
["runtime:stop ()","modules/lunatik.html#runtime:stop","lunatik · Stops the runtime and releases all associated kernel resources."],
["percpu:resume (...)","modules/lunatik.html#percpu:resume","lunatik · Resumes every runtime, as runtime:resume does, delivering the same objects to each."],
["percpu:stop ()","modules/lunatik.html#percpu:stop","lunatik · Closes the objects the runtimes share, then every runtime, releasing their Lua states."],
["lunatik.runner","modules/lunatik.runner.html","Module · Manages the execution and lifecycle of Lunatik scripts."],
["list ()","modules/lunatik.runner.html#list","lunatik.runner · Lists the names of all currently running scripts."],
["run (script[, context[, ispercpu]])","modules/lunatik.runner.html#run","lunatik.runner · Runs a Lunatik script in the current context."],
["shutdown ()","modules/lunatik.runner.html#shutdown","lunatik.runner · Shuts down all running scripts and their threads."],
["spawn (script)","modules/lunatik.runner.html#spawn","lunatik.runner · Spawns a Lunatik script in a new kernel thread."],
["startup ()","modules/lunatik.runner.html#startup","lunatik.runner · Initializes the runner's internal state."],
["stop (script)","modules/lunatik.runner.html#stop","lunatik.runner · Stops a running script and its associated thread, if any."],
["mailbox","modules/mailbox.html","Module · Inter-runtime communication mechanism using FIFOs and completions."],
["mailbox","modules/mailbox.html#mailbox","mailbox · The main mailbox table."],
["MailBox:receive ([timeout])","modules/mailbox.html#MailBox:receive","mailbox · Receives a message from the mailbox."],
["MailBox:send (message)","modules/mailbox.html#MailBox:send","mailbox · Sends a message to the mailbox."],
["mailbox:inbox (q, e)","modules/mailbox.html#mailbox:inbox","mailbox · Creates a new inbox (receive-only mailbox)."],
["mailbox:outbox (q, e)","modules/mailbox.html#mailbox:outbox","mailbox · Creates a new outbox (send-only mailbox)."],
["net","modules/net.html","Module · Network utility functions."],
["aton (addr)","modules/net.html#aton","net · Converts an IPv4 address string to its integer representation."],
["ntoa (ip)","modules/net.html#ntoa","net · Converts an integer representation of an IPv4 address to its string form."],
["netfilter","modules/netfilter.html","Module · Lua interface to the Linux Netfilter framework."],
["netfilter_hook:register (opts)","modules/netfilter.html#netfilter_hook:register","netfilter · Registers a Netfilter hook."],
["netlink.channel","modules/netlink.channel.html","Module · Generic netlink channel: a generic netlink family with one multicast group whose multicast/unicast are safe from softirq (netfilter hooks, XDP), for kernel-to-userspace delivery."],
["netlink.channel:multicast (cmd[, payload])","modules/netlink.channel.html#netlink.channel:multicast","netlink.channel · Multicasts a message to every subscriber of the channel's group."],
["netlink.channel:unicast (portid, cmd[, payload])","modules/netlink.channel.html#netlink.channel:unicast","netlink.channel · Unicasts a message to a single userspace subscriber by port id."],
["new (name)","modules/netlink.channel.html#new","netlink.channel · Creates a generic netlink channel."],
["netlink.genl","modules/netlink.genl.html","Module · Generic netlink (NETLINK_GENERIC) interface."],
["genl:call (family_id, cmd[, flags=0[, payload]])","modules/netlink.genl.html#genl:call","netlink.genl · Sends a single generic netlink command and returns the decoded reply messages."],
["genl:dump (family_id, cmd[, payload])","modules/netlink.genl.html#genl:dump","netlink.genl · Sends a dump command and collects the full multipart response."],
["genl:family (name)","modules/netlink.genl.html#genl:family","netlink.genl · Resolves a generic netlink family name to its (dynamically assigned) id."],
["genl:new ([o])","modules/netlink.genl.html#genl:new","netlink.genl · Creates a new genl object."],
["netlink","modules/netlink.html","Module · The netlink namespace."],
["channel (name)","modules/netlink.html#channel","netlink · Registers a generic netlink family with one multicast group; the returned channel's multicast/unicast are softirq-safe."],
["genl","modules/netlink.html#genl","netlink · Generic netlink session specialization."],
["nl80211","modules/netlink.html#nl80211","netlink · The nl80211 (wireless) namespace; groups the nl80211 object classes."],
["rt","modules/netlink.html#rt","netlink · The rtnetlink namespace; groups the NETLINK_ROUTE object classes."],
["netlink.message","modules/netlink.message.html","Module · Netlink wire codec shared by the netlink modules."],
["attrs (attrs[, pos=1])","modules/netlink.message.html#attrs","netlink.message · Attribute codec: serializes a {[type] = value} table into netlink attributes, or parses them back from a message body starting at pos."],
["encode (mtype, flags, seq, payload)","modules/netlink.message.html#encode","netlink.message · Builds a complete netlink message."],
["parse (buf)","modules/netlink.message.html#parse","netlink.message · Parses a buffer into a list of {type, flags, body} messages, where body holds the bytes after the nlmsghdr (family header and attributes)."],
["str ([value])","modules/netlink.message.html#str","netlink.message · Decodes a NUL-terminated string attribute value."],
["u32 ([value])","modules/netlink.message.html#u32","netlink.message · Decodes a u32 attribute value."],
["netlink.nl80211.ap","modules/netlink.nl80211.ap.html","Module · Access Point control."],
["ap:new ([o])","modules/netlink.nl80211.ap.html#ap:new","netlink.nl80211.ap · Creates a new ap object."],
["ap:start (opts)","modules/netlink.nl80211.ap.html#ap:start","netlink.nl80211.ap · Starts beaconing on an AP-mode interface (which must already be up)."],
["ap:stop (opts)","modules/netlink.nl80211.ap.html#ap:stop","netlink.nl80211.ap · Stops beaconing on an AP-mode interface."],
["netlink.nl80211","modules/netlink.nl80211.html","Module · The nl80211 (wireless) namespace."],
["netlink.nl80211.ap","modules/netlink.nl80211.html#netlink.nl80211.ap","netlink.nl80211 · Access Point control class."],
["netlink.nl80211.interface","modules/netlink.nl80211.html#netlink.nl80211.interface","netlink.nl80211 · Wireless interface class."],
["netlink.nl80211.station","modules/netlink.nl80211.html#netlink.nl80211.station","netlink.nl80211 · Station management class."],
["netlink.nl80211.wiphy","modules/netlink.nl80211.html#netlink.nl80211.wiphy","netlink.nl80211 · Wireless PHY (wiphy) class."],
["netlink.nl80211.interface","modules/netlink.nl80211.interface.html","Module · Wireless interface management."],
["interface:add (opts)","modules/netlink.nl80211.interface.html#interface:add","netlink.nl80211.interface · Adds a virtual interface to a wiphy."],
["interface:del (opts)","modules/netlink.nl80211.interface.html#interface:del","netlink.nl80211.interface · Deletes a virtual interface."],
["interface:list ()","modules/netlink.nl80211.interface.html#interface:list","netlink.nl80211.interface · Lists the wireless interfaces known to the kernel."],
["interface:new ([o])","modules/netlink.nl80211.interface.html#interface:new","netlink.nl80211.interface · Creates a new interface object."],
["netlink.nl80211.object","modules/netlink.nl80211.object.html","Module · Base class for the nl80211 object classes (wiphy, interface, ): a netlink.genl session bound to the \"nl80211\" family, caching its id and carrying the shared dump-decode loop."],
["object:__call ([pid])","modules/netlink.nl80211.object.html#object:__call","netlink.nl80211.object · Opens the genl socket, then resolves and caches the \"nl80211\" family id."],
["object:list ([payload])","modules/netlink.nl80211.object.html#object:list","netlink.nl80211.object · Dumps and decodes every record of the object type."],
["netlink.nl80211.station","modules/netlink.nl80211.station.html","Module · Station management."],
["station:add (opts)","modules/netlink.nl80211.station.html#station:add","netlink.nl80211.station · Adds a station to an AP interface."],
["station:del (opts)","modules/netlink.nl80211.station.html#station:del","netlink.nl80211.station · Removes a station from an AP interface."],
["station:list (ifindex)","modules/netlink.nl80211.station.html#station:list","netlink.nl80211.station · Lists the stations of an AP interface."],
["station:new ([o])","modules/netlink.nl80211.station.html#station:new","netlink.nl80211.station · Creates a new station object."],
["station:set (opts)","modules/netlink.nl80211.station.html#station:set","netlink.nl80211.station · Sets a station's authorized state, opening or closing its controlled port."],
["netlink.nl80211.wiphy","modules/netlink.nl80211.wiphy.html","Module · Wireless PHY (wiphy) listing."],
["wiphy:list ()","modules/netlink.nl80211.wiphy.html#wiphy:list","netlink.nl80211.wiphy · Lists the wireless PHYs (wiphys) known to the kernel."],
["wiphy:new ([o])","modules/netlink.nl80211.wiphy.html#wiphy:new","netlink.nl80211.wiphy · Creates a new wiphy object."],
["netlink.rt.addr","modules/netlink.rt.addr.html","Module · Interface address listing."],
["addr:list ([family=AF_UNSPEC])","modules/netlink.rt.addr.html#addr:list","netlink.rt.addr · Lists all interface addresses from the kernel."],
["addr:new ([o])","modules/netlink.rt.addr.html#addr:new","netlink.rt.addr · Creates a new addr object."],
["netlink.rt","modules/netlink.rt.html","Module · The rtnetlink namespace."],
["netlink.rt.addr","modules/netlink.rt.html#netlink.rt.addr","netlink.rt · Interface address class."],
["netlink.rt.link","modules/netlink.rt.html#netlink.rt.link","netlink.rt · Network interface (link) class."],
["netlink.rt.route","modules/netlink.rt.html#netlink.rt.route","netlink.rt · Kernel routing table class."],
["netlink.rt.rule","modules/netlink.rt.html#netlink.rt.rule","netlink.rt · FIB rule (policy routing) class."],
["netlink.rt.link","modules/netlink.rt.link.html","Module · Network interface (link) management."],
["link:list ()","modules/netlink.rt.link.html#link:list","netlink.rt.link · Lists all network interfaces from the kernel."],
["link:new ([o])","modules/netlink.rt.link.html#link:new","netlink.rt.link · Creates a new link object."],
["link:set (opts)","modules/netlink.rt.link.html#link:set","netlink.rt.link · Sets an interface's administrative up state."],
["netlink.rt.object","modules/netlink.rt.object.html","Module · Base class for the rtnetlink object classes (route, link, addr, rule): a netlink.session over the NETLINK_ROUTE protocol carrying the shared dump loop and the routing-table id split."],
["list ([family=AF_UNSPEC])","modules/netlink.rt.object.html#list","netlink.rt.object · Dumps and decodes every record of the object type."],
["netlink.rt.route","modules/netlink.rt.route.html","Module · Kernel routing table interface."],
["route:add (opts)","modules/netlink.rt.route.html#route:add","netlink.rt.route · Adds a route to the kernel routing table."],
["route:del (opts)","modules/netlink.rt.route.html#route:del","netlink.rt.route · Deletes a route from the kernel routing table."],
["route:list ([family=AF_UNSPEC])","modules/netlink.rt.route.html#route:list","netlink.rt.route · Lists all routes from the kernel routing tables."],
["route:new ([o])","modules/netlink.rt.route.html#route:new","netlink.rt.route · Creates a new route object."],
["netlink.rt.rule","modules/netlink.rt.rule.html","Module · FIB rule (policy routing) interface."],
["rule:add (opts)","modules/netlink.rt.rule.html#rule:add","netlink.rt.rule · Adds a FIB rule directing matching lookups to a routing table."],
["rule:del (opts)","modules/netlink.rt.rule.html#rule:del","netlink.rt.rule · Deletes a FIB rule matching the given parameters."],
["rule:list ([family=AF_UNSPEC])","modules/netlink.rt.rule.html#rule:list","netlink.rt.rule · Lists all FIB rules from the kernel."],
["rule:new ([o])","modules/netlink.rt.rule.html#rule:new","netlink.rt.rule · Creates a new rule object."],
["netlink.session","modules/netlink.session.html","Module · Netlink request/response session."],
["session:__call ([pid])","modules/netlink.session.html#session:__call","netlink.session · Creates a session backed by an AF_NETLINK socket of the class's proto."],
["session:close ()","modules/netlink.session.html#session:close","netlink.session · Closes the underlying socket."],
["session:dump (mtype, payload)","modules/netlink.session.html#session:dump","netlink.session · Sends a dump request and drains the multipart reply until NLMSG_DONE."],
["session:new ([o])","modules/netlink.session.html#session:new","netlink.session · Creates a new session object."],
["session:request (mtype, flags, payload)","modules/netlink.session.html#session:request","netlink.session · Sends one request (NLM_F_REQUEST plus flags) with a fresh sequence number, without waiting for a reply."],
["session:talk (mtype[, flags=0], payload)","modules/netlink.session.html#session:talk","netlink.session · Sends a request with NLM_F_ACK and drains the reply up to the kernel acknowledgment, keeping the socket in sync."],
["notifier","modules/notifier.html","Module · Notifier chain mechanism."],
["notifier:stop ()","modules/notifier.html#notifier:stop","notifier · Stops event delivery to the Lua callback."],
["keyboard (callback)","modules/notifier.html#keyboard","notifier · Registers a keyboard-event notifier."],
["netdevice (callback)","modules/notifier.html#netdevice","notifier · Registers a network-device notifier."],
["vterm (callback)","modules/notifier.html#vterm","notifier · Registers a virtual-terminal notifier."],
["probe","modules/probe.html","Module · kprobes interface."],
["probe:enable (flag)","modules/probe.html#probe:enable","probe · Enables or disables the probe."],
["probe:new (symbol, handlers)","modules/probe.html#probe:new","probe · Creates and registers a new kprobe."],
["probe:stop ()","modules/probe.html#probe:stop","probe · Unregisters and stops the probe."],
["rcu","modules/rcu.html","Module · RCU-synchronized hash table."],
["rcu_table:__index (key)","modules/rcu.html#rcu_table:__index","rcu · Retrieves a value from the table (RCU-protected, lockless)."],
["rcu_table:__newindex (key, value)","modules/rcu.html#rcu_table:__newindex","rcu · Sets or removes a value in the table (serialized)."],
["rcu_table:map (callback)","modules/rcu.html#rcu_table:map","rcu · Iterates over the table calling callback(key, value) for each entry."],
["table ([size=256])","modules/rcu.html#table","rcu · Creates a new RCU hash table."],
["sched","modules/sched.html","Module · Linux Extensible Scheduler (sched_ext) integration."],
["sched_ctx:dsq (dsq)","modules/sched.html#sched_ctx:dsq","sched · Sets the sched_ext dispatch queue for this task."],
["sched_ctx:slice (slice)","modules/sched.html#sched_ctx:slice","sched · Sets the sched_ext slice in nanoseconds for this task."],
["sched_ctx:task ()","modules/sched.html#sched_ctx:task","sched · Returns the object for the current task."],
["attach (callback)","modules/sched.html#attach","sched · Registers a Lua callback function to be invoked by a sched_ext eBPF program."],
["detach ()","modules/sched.html#detach","sched · Unregisters the Lua callback function associated with the current Lunatik runtime."],
["set","modules/set.html","Module · A set is a compact, immutable set of strings, queried by binary search."],
["__len ()","modules/set.html#__len","set · Returns the number of members."],
["set:has (s)","modules/set.html#set:has","set · Returns whether a string is in the set."],
["set:new (strings)","modules/set.html#set:new","set · Builds a plain set from an array of strings."],
["set.labeled:labeled (t)","modules/set.html#set.labeled:labeled","set · Builds a labeled set from a table of members, each with a label bitmask."],
["set.labeled:match (s)","modules/set.html#set.labeled:match","set · Returns the union of the labels of s and its suffixes, or 0."],
["signal","modules/signal.html","Module · POSIX Signals"],
["kill (pid[, sig])","modules/signal.html#kill","signal · Sends a signal to a process."],
["sigmask (sig[, cmd])","modules/signal.html#sigmask","signal · Modifies signal mask for current task."],
["sigpending ()","modules/signal.html#sigpending","signal · Checks if the current task has pending signals."],
["sigstate (sig[, state])","modules/signal.html#sigstate","signal · Checks signal state for current task."],
["skb","modules/skb.html","Module · Linux socket buffer interface."],
["skb:__len ()","modules/skb.html#skb:__len","skb · "],
["skb:checksum ()","modules/skb.html#skb:checksum","skb · Recomputes IP and transport-layer (TCP/UDP) checksums."],
["skb:connmark ([value])","modules/skb.html#skb:connmark","skb · Gets or sets the conntrack mark: with no argument reads it, with value sets it."],
["skb:copy ()","modules/skb.html#skb:copy","skb · Returns an independent copy of the skb with its own data buffer."],
["skb:data ([layer])","modules/skb.html#skb:data","skb · "],
["skb:forward ()","modules/skb.html#skb:forward","skb · Forwards the skb out through its ingress device."],
["skb:ifindex ()","modules/skb.html#skb:ifindex","skb · "],
["skb:mark ([value])","modules/skb.html#skb:mark","skb · Gets or sets the packet mark: with no argument reads it, with value sets it."],
["skb:priority ([value])","modules/skb.html#skb:priority","skb · Gets or sets the packet priority: with no argument reads it, with value sets it."],
["skb:resize (n)","modules/skb.html#skb:resize","skb · Expands (skb_put) or shrinks (skb_trim) the skb data area."],
["skb:vlan ()","modules/skb.html#skb:vlan","skb · "],
["socket","modules/socket.html","Module · Low-level Lua interface for kernel networking sockets."],
["socket:accept (self[, flags=0])","modules/socket.html#socket:accept","socket · Accepts a connection on a listening socket."],
["socket:bind (addr[, port])","modules/socket.html#socket:bind","socket · Binds the socket to a local address."],
["socket:close ()","modules/socket.html#socket:close","socket · Closes the socket."],
["socket:connect (addr[, port[, flags=0]])","modules/socket.html#socket:connect","socket · Initiates a connection on a socket."],
["socket:getpeername ()","modules/socket.html#socket:getpeername","socket · Gets the address of the peer to which the socket is connected."],
["socket:getsockname ()","modules/socket.html#socket:getsockname","socket · Gets the local address to which the socket is bound."],
["socket:listen ([backlog])","modules/socket.html#socket:listen","socket · Puts a connection-oriented socket into the listening state."],
["socket:receive (length[, flags=0[, from=false]])","modules/socket.html#socket:receive","socket · Receives a message from the socket."],
["socket:send (message[, addr[, port]])","modules/socket.html#socket:send","socket · Sends a message through the socket."],
["socket:setsockopt (level, optname, value)","modules/socket.html#socket:setsockopt","socket · Sets a socket option."],
["new (family, type, protocol[, pid])","modules/socket.html#new","socket · Creates a new socket object."],
["socket.inet","modules/socket.inet.html","Module · Internet (AF_INET) socket operations."],
["inet.tcp","modules/socket.inet.html#inet.tcp","socket.inet · TCP socket specialization."],
["inet.tcp:accept (flags)","modules/socket.inet.html#inet.tcp:accept","socket.inet · Accepts an incoming connection on a listening TCP socket."],
["inet.tcp:listen (backlog)","modules/socket.inet.html#inet.tcp:listen","socket.inet · Listens for incoming connections on a TCP socket."],
["inet.udp","modules/socket.inet.html#inet.udp","socket.inet · UDP socket specialization."],
["inet.udp:receivefrom (len, flags)","modules/socket.inet.html#inet.udp:receivefrom","socket.inet · Receives data from a UDP socket, along with the sender's address."],
["inet.udp:sendto (msg, addr, port)","modules/socket.inet.html#inet.udp:sendto","socket.inet · Alias for inet.udp:send."],
["inet:__call ()","modules/socket.inet.html#inet:__call","socket.inet · Metamethod to create a new socket instance when inet() or inet.tcp() or inet.udp() is called."],
["inet:bind (addr, port)","modules/socket.inet.html#inet:bind","socket.inet · Binds the socket to a specific address and port."],
["inet:close ()","modules/socket.inet.html#inet:close","socket.inet · Closes the underlying socket."],
["inet:connect (addr, port, flags)","modules/socket.inet.html#inet:connect","socket.inet · Connects the socket to a remote address and port."],
["inet:getpeername ()","modules/socket.inet.html#inet:getpeername","socket.inet · Gets the remote address (IP and port) to which the socket is connected."],
["inet:getsockname ()","modules/socket.inet.html#inet:getsockname","socket.inet · Gets the local address (IP and port) to which the socket is bound."],
["inet:new ([o])","modules/socket.inet.html#inet:new","socket.inet · Creates a new inet socket object."],
["inet:receive (...)","modules/socket.inet.html#inet:receive","socket.inet · Receives data from the socket."],
["inet:send (msg, addr, port)","modules/socket.inet.html#inet:send","socket.inet · Sends data through the socket."],
["socket.raw","modules/socket.raw.html","Module · RAW AF_PACKET socket operations."],
["bind (proto, ifindex)","modules/socket.raw.html#bind","socket.raw · Creates and binds a raw packet socket for receiving frames."],
["socket.unix","modules/socket.unix.html","Module · UNIX domain socket (AF_UNIX) operations."],
["unix.dgram","modules/socket.unix.html#unix.dgram","socket.unix · DGRAM socket specialization (connectionless)."],
["unix.dgram:receivefrom (len, flags)","modules/socket.unix.html#unix.dgram:receivefrom","socket.unix · Receives data from a DGRAM socket along with the sender's path."],
["unix.dgram:sendto (msg, path)","modules/socket.unix.html#unix.dgram:sendto","socket.unix · Sends data to a UNIX domain socket path."],
["unix.stream","modules/socket.unix.html#unix.stream","socket.unix · STREAM socket specialization (connection-oriented)."],
["unix.stream:accept (flags)","modules/socket.unix.html#unix.stream:accept","socket.unix · Accepts an incoming connection on a listening STREAM socket."],
["unix.stream:listen (backlog)","modules/socket.unix.html#unix.stream:listen","socket.unix · Listens for incoming connections on a STREAM socket."],
["unix:__call (path)","modules/socket.unix.html#unix:__call","socket.unix · Creates a new UNIX domain socket instance."],
["unix:bind (path)","modules/socket.unix.html#unix:bind","socket.unix · Binds the socket to a UNIX domain path."],
["unix:close ()","modules/socket.unix.html#unix:close","socket.unix · Closes the underlying socket."],
["unix:connect (path)","modules/socket.unix.html#unix:connect","socket.unix · Connects the socket to a UNIX domain path."],
["unix:getpeername ()","modules/socket.unix.html#unix:getpeername","socket.unix · Gets the remote address (path) the socket is connected to."],
["unix:getsockname ()","modules/socket.unix.html#unix:getsockname","socket.unix · Gets the local address (path) of the socket."],
["unix:new ([o])","modules/socket.unix.html#unix:new","socket.unix · Creates a new unix socket object."],
["unix:receive (...)","modules/socket.unix.html#unix:receive","socket.unix · Receives data from the socket."],
["unix:send (msg, path)","modules/socket.unix.html#unix:send","socket.unix · Sends data through the socket."],
["struct","modules/struct.html","Module · Binary codec for fixed C struct layouts."],
["fieldsize (name)","modules/struct.html#fieldsize","struct · Returns the size in bytes of a named field."],
["pack (...)","modules/struct.html#pack","struct · Serializes the field values (in offset order) into the struct's bytes."],
["unpack (buf[, pos])","modules/struct.html#unpack","struct · Deserializes the struct's fields from a buffer."],
["syscall","modules/syscall.html","Module · Accessing kernel system call information."],
["address (syscall_number)","modules/syscall.html#address","syscall · Retrieves the kernel address of a system call."],
["syscall.table","modules/syscall.table.html","Module · A table mapping system call names to their kernel addresses."],
["task","modules/task.html","Module · Linux task interface."],
["task:comm ()","modules/task.html#task:comm","task · Returns the command name (comm) of the task, i.e., the executable."],
["task:cpu ()","modules/task.html#task:cpu","task · Returns the CPU the task last ran on."],
["task:current ()","modules/task.html#task:current","task · Gets an object representing the current kernel task."],
["task:pid ()","modules/task.html#task:pid","task · Returns the process ID (PID) of the task."],
["task:prio ()","modules/task.html#task:prio","task · Returns the dynamic priority of the task."],
["task:tgid ()","modules/task.html#task:tgid","task · Returns the thread group ID (TGID) of the task."],
["tc","modules/tc.html","Module · Linux Traffic Control (TC) integration."],
["tc_ctx:action (action)","modules/tc.html#tc_ctx:action","tc · Sets the TC verdict action for this packet."],
["tc_ctx:argument ()","modules/tc.html#tc_ctx:argument","tc · Returns the argument data buffer passed from eBPF."],
["tc_ctx:skb ()","modules/tc.html#tc_ctx:skb","tc · Returns the packet object for the current TC context."],
["attach (callback)","modules/tc.html#attach","tc · Registers a Lua callback function to be invoked by a TC/eBPF program."],
["detach ()","modules/tc.html#detach","tc · Unregisters the Lua callback function associated with the current Lunatik runtime."],
["thread","modules/thread.html","Module · Kernel thread primitives."],
["thread:current ()","modules/thread.html#thread:current","thread · Gets a thread object representing the current kernel task."],
["thread:run (runtime, name, ...)","modules/thread.html#thread:run","thread · Creates and starts a new kernel thread to run a Lua task."],
["thread:shouldstop ()","modules/thread.html#thread:shouldstop","thread · Checks if the current thread has been signaled to stop."],
["thread:stop (self)","modules/thread.html#thread:stop","thread · Stops a running kernel thread."],
["thread:task (self)","modules/thread.html#thread:task","thread · Returns a task object for the kernel task associated with the thread."],
["xdp","modules/xdp.html","Module · eXpress Data Path (XDP) integration."],
["xdp_ctx:action (action)","modules/xdp.html#xdp_ctx:action","xdp · Sets the XDP verdict action for this packet."],
["xdp_ctx:argument ()","modules/xdp.html#xdp_ctx:argument","xdp · Returns the argument data buffer passed from eBPF."],
["xdp_ctx:packet ()","modules/xdp.html#xdp_ctx:packet","xdp · Returns the packet data buffer for the current XDP context."],
["attach (callback)","modules/xdp.html#attach","xdp · Registers a Lua callback function to be invoked by an XDP/eBPF program."],
["detach ()","modules/xdp.html#detach","xdp · Unregisters the Lua callback function associated with the current Lunatik runtime."],
["crypto.hkdf","classes/crypto.hkdf.html","Class · HMAC-based Extract-and-Expand Key Derivation Function (HKDF) based on RFC 5869."],
["HKDF.new (alg)","classes/crypto.hkdf.html#HKDF.new","crypto.hkdf · Creates a new HKDF instance for a given hash algorithm."],
["HKDF:close ()","classes/crypto.hkdf.html#HKDF:close","crypto.hkdf · Closes the HKDF instance and releases the underlying HMAC transform."],
["HKDF:expand (prk[, info], length)","classes/crypto.hkdf.html#HKDF:expand","crypto.hkdf · Performs the HKDF Expand step."],
["HKDF:extract ([salt], ikm)","classes/crypto.hkdf.html#HKDF:extract","crypto.hkdf · Performs the HKDF Extract step."],
["HKDF:hkdf ([salt], ikm[, info], length)","classes/crypto.hkdf.html#HKDF:hkdf","crypto.hkdf · Performs the full HKDF (Extract and Expand) operation."],
["HKDF:hmac (key, data)","classes/crypto.hkdf.html#HKDF:hmac","crypto.hkdf · Performs an HMAC calculation using the instance's algorithm."],
["crypto_aead","classes/crypto_aead.html","Class · Lua interface to AEAD (Authenticated Encryption with Associated Data) ciphers."],
["crypto_aead:authsize ()","classes/crypto_aead.html#crypto_aead:authsize","crypto_aead · Returns the authentication tag size in bytes."],
["crypto_aead:decrypt (iv, ciphertext_with_tag[, aad])","classes/crypto_aead.html#crypto_aead:decrypt","crypto_aead · Decrypts and authenticates ciphertext."],
["crypto_aead:encrypt (iv, plaintext[, aad])","classes/crypto_aead.html#crypto_aead:encrypt","crypto_aead · Encrypts plaintext with authentication."],
["crypto_aead:ivsize ()","classes/crypto_aead.html#crypto_aead:ivsize","crypto_aead · Returns the required IV size in bytes."],
["crypto_aead:new (algname)","classes/crypto_aead.html#crypto_aead:new","crypto_aead · Creates a new AEAD transform object."],
["crypto_aead:setauthsize (tagsize)","classes/crypto_aead.html#crypto_aead:setauthsize","crypto_aead · Sets the authentication tag size."],
["crypto_aead:setkey (key)","classes/crypto_aead.html#crypto_aead:setkey","crypto_aead · Sets the cipher key."],
["crypto_comp","classes/crypto_comp.html","Class · Lua interface to synchronous compression algorithms."],
["crypto_comp:compress (data, max_len)","classes/crypto_comp.html#crypto_comp:compress","crypto_comp · Compresses data."],
["crypto_comp:decompress (data, max_len)","classes/crypto_comp.html#crypto_comp:decompress","crypto_comp · Decompresses data."],
["crypto_comp:new (algname)","classes/crypto_comp.html#crypto_comp:new","crypto_comp · Creates a new COMP transform object."],
["crypto_rng","classes/crypto_rng.html","Class · Lua interface to synchronous Random Number Generators (RNG)."],
["crypto_rng:generate (n[, seed])","classes/crypto_rng.html#crypto_rng:generate","crypto_rng · Generates random bytes, optionally reseeding first."],
["crypto_rng:getbytes (n)","classes/crypto_rng.html#crypto_rng:getbytes","crypto_rng · Generates random bytes without reseeding."],
["crypto_rng:info ()","classes/crypto_rng.html#crypto_rng:info","crypto_rng · Returns algorithm information."],
["crypto_rng:new ([algname])","classes/crypto_rng.html#crypto_rng:new","crypto_rng · Creates a new RNG object."],
["crypto_rng:reset (seed)","classes/crypto_rng.html#crypto_rng:reset","crypto_rng · Reseeds the RNG."],
["crypto_shash","classes/crypto_shash.html","Class · Lua interface to synchronous message digest (hash) algorithms, including HMAC."],
["crypto_shash:digest (data)","classes/crypto_shash.html#crypto_shash:digest","crypto_shash · Computes the digest of data in a single call."],
["crypto_shash:digestsize ()","classes/crypto_shash.html#crypto_shash:digestsize","crypto_shash · Returns the digest size in bytes."],
["crypto_shash:export ()","classes/crypto_shash.html#crypto_shash:export","crypto_shash · Exports the current internal hash state."],
["crypto_shash:final ()","classes/crypto_shash.html#crypto_shash:final","crypto_shash · Finalizes and returns the digest."],
["crypto_shash:finup (data)","classes/crypto_shash.html#crypto_shash:finup","crypto_shash · Feeds final data and returns the digest (update + final in one call)."],
["crypto_shash:import (state)","classes/crypto_shash.html#crypto_shash:import","crypto_shash · Restores a previously exported hash state."],
["crypto_shash:init ()","classes/crypto_shash.html#crypto_shash:init","crypto_shash · Initializes the hash state for incremental hashing."],
["crypto_shash:new (algname)","classes/crypto_shash.html#crypto_shash:new","crypto_shash · Creates a new SHASH object."],
["crypto_shash:setkey (key)","classes/crypto_shash.html#crypto_shash:setkey","crypto_shash · Sets the key (required for HMAC algorithms)."],
["crypto_shash:update (data)","classes/crypto_shash.html#crypto_shash:update","crypto_shash · Feeds data into the running hash."],
["crypto_skcipher","classes/crypto_skcipher.html","Class · Lua interface to symmetric-key ciphers (SKCIPHER)."],
["crypto_skcipher:blocksize ()","classes/crypto_skcipher.html#crypto_skcipher:blocksize","crypto_skcipher · Returns the cipher block size in bytes."],
["crypto_skcipher:decrypt (iv, data)","classes/crypto_skcipher.html#crypto_skcipher:decrypt","crypto_skcipher · Decrypts data."],
["crypto_skcipher:encrypt (iv, data)","classes/crypto_skcipher.html#crypto_skcipher:encrypt","crypto_skcipher · Encrypts data."],
["crypto_skcipher:ivsize ()","classes/crypto_skcipher.html#crypto_skcipher:ivsize","crypto_skcipher · Returns the required IV size in bytes."],
["crypto_skcipher:new (algname)","classes/crypto_skcipher.html#crypto_skcipher:new","crypto_skcipher · Creates a new SKCIPHER transform object."],
["crypto_skcipher:setkey (key)","classes/crypto_skcipher.html#crypto_skcipher:setkey","crypto_skcipher · Sets the cipher key."],
["skb.attr","classes/skb.attr.html","Class · Attribute view over an skb: reads and writes packet fields as table keys (view.mark, view.priority) instead of method calls."],
["skb.attr:new (skb)","classes/skb.attr.html#skb.attr:new","skb.attr · Wraps an skb in an attribute view."],
["Getting started","topics/01-getting-started.md.html","Guide"],
["Check the install","topics/01-getting-started.md.html#check-the-install","Guide · Getting started"],
["After a kernel upgrade","topics/01-getting-started.md.html#after-a-kernel-upgrade","Guide · Getting started"],
["Uninstall","topics/01-getting-started.md.html#uninstall","Guide · Getting started"],
["OpenWRT","topics/01-getting-started.md.html#openwrt","Guide · Getting started"],
["First steps","topics/01-getting-started.md.html#first-steps","Guide · Getting started"],
["Running scripts","topics/02-running-scripts.md.html","Guide"],
["The lunatik command","topics/02-running-scripts.md.html#the-lunatik-command","Guide · Running scripts"],
["Execution contexts","topics/02-running-scripts.md.html#execution-contexts","Guide · Running scripts"],
["Kernel threads","topics/02-running-scripts.md.html#kernel-threads","Guide · Running scripts"],
["lunatic","topics/02-running-scripts.md.html#lunatic","Guide · Running scripts"],
["Per-CPU scripts","topics/03-percpu.md.html","Guide"],
["Lua in the kernel","topics/04-lua.md.html","Guide"],
["Floating-point numbers","topics/04-lua.md.html#floating-point-numbers","Guide · Lua in the kernel"],
["Lua API","topics/04-lua.md.html#lua-api","Guide · Lua in the kernel"],
["Softirq and hardirq runtimes","topics/04-lua.md.html#softirq-and-hardirq-runtimes","Guide · Lua in the kernel"],
["Examples","topics/05-examples.md.html","Guide"],
["Packet filtering and classification","topics/05-examples.md.html#packet-filtering-and-classification","Guide · Examples"],
["Network monitoring and control","topics/05-examples.md.html#network-monitoring-and-control","Guide · Examples"],
["Servers and shared state","topics/05-examples.md.html#servers-and-shared-state","Guide · Examples"],
["Tracing","topics/05-examples.md.html#tracing","Guide · Examples"],
["Input devices","topics/05-examples.md.html#input-devices","Guide · Examples"],
["Filesystem","topics/05-examples.md.html#filesystem","Guide · Examples"],
["Development","topics/06-development.md.html","Guide"],
["Testing","topics/06-development.md.html#testing","Guide · Development"],
["Contributing","topics/06-development.md.html#contributing","Guide · Development"],
["Resources","topics/07-resources.md.html","Guide"],
["Talks and papers","topics/07-resources.md.html#talks-and-papers","Guide · Resources"],
["Articles","topics/07-resources.md.html#articles","Guide · Resources"],
["Google Summer of Code","topics/07-resources.md.html#google-summer-of-code","Guide · Resources"],
["Code and manuals","topics/07-resources.md.html#code-and-manuals","Guide · Resources"],
["Works that cite Lunatik","topics/07-resources.md.html#works-that-cite-lunatik","Guide · Resources"],
["Press and community","topics/07-resources.md.html#press-and-community","Guide · Resources"],
["Related work","topics/07-resources.md.html#related-work","Guide · Resources"],
["Lunatik C API","topics/capi.md.html","Guide"],
["Types","topics/capi.md.html#types","Guide · Lunatik C API"],
["lunatik_class_t","topics/capi.md.html#lunatik_class_t","Guide · Lunatik C API"],
["lunatik_object_t","topics/capi.md.html#lunatik_object_t","Guide · Lunatik C API"],
["lunatik_opt_t","topics/capi.md.html#lunatik_opt_t","Guide · Lunatik C API"],
["Runtime","topics/capi.md.html#runtime","Guide · Lunatik C API"],
["lunatik_runtime","topics/capi.md.html#lunatik_runtime","Guide · Lunatik C API"],
["lunatik_stop","topics/capi.md.html#lunatik_stop","Guide · Lunatik C API"],
["lunatik_copyobjects","topics/capi.md.html#lunatik_copyobjects","Guide · Lunatik C API"],
["lunatik_run","topics/capi.md.html#lunatik_run","Guide · Lunatik C API"],
["lunatik_handle","topics/capi.md.html#lunatik_handle","Guide · Lunatik C API"],
["lunatik_cpcall","topics/capi.md.html#lunatik_cpcall","Guide · Lunatik C API"],
["lunatik_toruntime","topics/capi.md.html#lunatik_toruntime","Guide · Lunatik C API"],
["lunatik_getstate","topics/capi.md.html#lunatik_getstate","Guide · Lunatik C API"],
["lunatik_class","topics/capi.md.html#lunatik_class","Guide · Lunatik C API"],
["lunatik_env","topics/capi.md.html#lunatik_env","Guide · Lunatik C API"],
["lunatik_isready","topics/capi.md.html#lunatik_isready","Guide · Lunatik C API"],
["lunatik_isowner","topics/capi.md.html#lunatik_isowner","Guide · Lunatik C API"],
["lunatik_isrtnl","topics/capi.md.html#lunatik_isrtnl","Guide · Lunatik C API"],
["lunatik_iskthread","topics/capi.md.html#lunatik_iskthread","Guide · Lunatik C API"],
["lunatik_checkruntime","topics/capi.md.html#lunatik_checkruntime","Guide · Lunatik C API"],
["lunatik_setruntime","topics/capi.md.html#lunatik_setruntime","Guide · Lunatik C API"],
["lunatik_checkcontext","topics/capi.md.html#lunatik_checkcontext","Guide · Lunatik C API"],
["lunatik_checkclass","topics/capi.md.html#lunatik_checkclass","Guide · Lunatik C API"],
["lunatik_cannotsleep","topics/capi.md.html#lunatik_cannotsleep","Guide · Lunatik C API"],
["lunatik_checkarmed","topics/capi.md.html#lunatik_checkarmed","Guide · Lunatik C API"],
["lunatik_checkrtnl","topics/capi.md.html#lunatik_checkrtnl","Guide · Lunatik C API"],
["lunatik_checkowner","topics/capi.md.html#lunatik_checkowner","Guide · Lunatik C API"],
["lunatik_percpudata","topics/capi.md.html#lunatik_percpudata","Guide · Lunatik C API"],
["LUNATIK_PERCPUDATA (macro)","topics/capi.md.html#lunatik_percpudata-macro","Guide · Lunatik C API"],
["lunatik_getpercpu","topics/capi.md.html#lunatik_getpercpu","Guide · Lunatik C API"],
["lunatik_getcpu","topics/capi.md.html#lunatik_getcpu","Guide · Lunatik C API"],
["lunatik_checkpercpu","topics/capi.md.html#lunatik_checkpercpu","Guide · Lunatik C API"],
["Object Lifecycle","topics/capi.md.html#object-lifecycle","Guide · Lunatik C API"],
["lunatik_newobject","topics/capi.md.html#lunatik_newobject","Guide · Lunatik C API"],
["lunatik_createobject","topics/capi.md.html#lunatik_createobject","Guide · Lunatik C API"],
["lunatik_cloneobject","topics/capi.md.html#lunatik_cloneobject","Guide · Lunatik C API"],
["lunatik_pushobject","topics/capi.md.html#lunatik_pushobject","Guide · Lunatik C API"],
["lunatik_getobject","topics/capi.md.html#lunatik_getobject","Guide · Lunatik C API"],
["lunatik_getobject_rcu","topics/capi.md.html#lunatik_getobject_rcu","Guide · Lunatik C API"],
["lunatik_putobject","topics/capi.md.html#lunatik_putobject","Guide · Lunatik C API"],
["lunatik_closeobject","topics/capi.md.html#lunatik_closeobject","Guide · Lunatik C API"],
["Object Access","topics/capi.md.html#object-access","Guide · Lunatik C API"],
["lunatik_checkobject","topics/capi.md.html#lunatik_checkobject","Guide · Lunatik C API"],
["lunatik_toobject","topics/capi.md.html#lunatik_toobject","Guide · Lunatik C API"],
["lunatik_checkshareable","topics/capi.md.html#lunatik_checkshareable","Guide · Lunatik C API"],
["LUNATIK_PRIVATECHECKER","topics/capi.md.html#lunatik_privatechecker","Guide · Lunatik C API"],
["lunatik_argcheckclass","topics/capi.md.html#lunatik_argcheckclass","Guide · Lunatik C API"],
["lunatik_checkobjectclass","topics/capi.md.html#lunatik_checkobjectclass","Guide · Lunatik C API"],
["Locking","topics/capi.md.html#locking","Guide · Lunatik C API"],
["lunatik_lock","topics/capi.md.html#lunatik_lock","Guide · Lunatik C API"],
["lunatik_lockkillable","topics/capi.md.html#lunatik_lockkillable","Guide · Lunatik C API"],
["lunatik_closeprivate","topics/capi.md.html#lunatik_closeprivate","Guide · Lunatik C API"],
["Registry and Attach/Detach","topics/capi.md.html#registry-and-attachdetach","Guide · Lunatik C API"],
["lunatik_register","topics/capi.md.html#lunatik_register","Guide · Lunatik C API"],
["lunatik_unregister","topics/capi.md.html#lunatik_unregister","Guide · Lunatik C API"],
["lunatik_registerobject","topics/capi.md.html#lunatik_registerobject","Guide · Lunatik C API"],
["lunatik_unregisterobject","topics/capi.md.html#lunatik_unregisterobject","Guide · Lunatik C API"],
["lunatik_getregistry","topics/capi.md.html#lunatik_getregistry","Guide · Lunatik C API"],
["lunatik_getregistryobject","topics/capi.md.html#lunatik_getregistryobject","Guide · Lunatik C API"],
["lunatik_setflag","topics/capi.md.html#lunatik_setflag","Guide · Lunatik C API"],
["lunatik_getflag","topics/capi.md.html#lunatik_getflag","Guide · Lunatik C API"],
["lunatik_seedflag","topics/capi.md.html#lunatik_seedflag","Guide · Lunatik C API"],
["lunatik_attach","topics/capi.md.html#lunatik_attach","Guide · Lunatik C API"],
["lunatik_detach","topics/capi.md.html#lunatik_detach","Guide · Lunatik C API"],
["Error Handling","topics/capi.md.html#error-handling","Guide · Lunatik C API"],
["lunatik_throw","topics/capi.md.html#lunatik_throw","Guide · Lunatik C API"],
["lunatik_pusherrname","topics/capi.md.html#lunatik_pusherrname","Guide · Lunatik C API"],
["lunatik_try","topics/capi.md.html#lunatik_try","Guide · Lunatik C API"],
["lunatik_tryret","topics/capi.md.html#lunatik_tryret","Guide · Lunatik C API"],
["lunatik_errmsg","topics/capi.md.html#lunatik_errmsg","Guide · Lunatik C API"],
["Table Fields","topics/capi.md.html#table-fields","Guide · Lunatik C API"],
["lunatik_checkfield","topics/capi.md.html#lunatik_checkfield","Guide · Lunatik C API"],
["lunatik_optcfunction","topics/capi.md.html#lunatik_optcfunction","Guide · Lunatik C API"],
["lunatik_setinteger","topics/capi.md.html#lunatik_setinteger","Guide · Lunatik C API"],
["lunatik_optinteger","topics/capi.md.html#lunatik_optinteger","Guide · Lunatik C API"],
["lunatik_setstring","topics/capi.md.html#lunatik_setstring","Guide · Lunatik C API"],
["Values","topics/capi.md.html#values","Guide · Lunatik C API"],
["lunatik_checkbounds","topics/capi.md.html#lunatik_checkbounds","Guide · Lunatik C API"],
["lunatik_pushstring","topics/capi.md.html#lunatik_pushstring","Guide · Lunatik C API"],
["lunatik_pushoptinteger","topics/capi.md.html#lunatik_pushoptinteger","Guide · Lunatik C API"],
["lunatik_value_t","topics/capi.md.html#lunatik_value_t","Guide · Lunatik C API"],
["Module Definition","topics/capi.md.html#module-definition","Guide · Lunatik C API"],
["LUNATIK_OPENER","topics/capi.md.html#lunatik_opener","Guide · Lunatik C API"],
["LUNATIK_CLASSES","topics/capi.md.html#lunatik_classes","Guide · Lunatik C API"],
["LUNATIK_NEWLIB","topics/capi.md.html#lunatik_newlib","Guide · Lunatik C API"],
["Writing a binding","topics/capi.md.html#writing-a-binding","Guide · Lunatik C API"],
["Memory","topics/capi.md.html#memory","Guide · Lunatik C API"],
["lunatik_malloc","topics/capi.md.html#lunatik_malloc","Guide · Lunatik C API"],
["lunatik_realloc","topics/capi.md.html#lunatik_realloc","Guide · Lunatik C API"],
["lunatik_free","topics/capi.md.html#lunatik_free","Guide · Lunatik C API"],
["lunatik_checkalloc","topics/capi.md.html#lunatik_checkalloc","Guide · Lunatik C API"],
["lunatik_gfp","topics/capi.md.html#lunatik_gfp","Guide · Lunatik C API"],
["eBPF bindings","topics/capi.md.html#ebpf-bindings","Guide · Lunatik C API"],
["LUNATIK_EBPF_RUN","topics/capi.md.html#lunatik_ebpf_run","Guide · Lunatik C API"],
["lunatik_ebpf_bind","topics/capi.md.html#lunatik_ebpf_bind","Guide · Lunatik C API"],
["lunatik_ebpf_attach","topics/capi.md.html#lunatik_ebpf_attach","Guide · Lunatik C API"],
["LUNATIK_EBPF_NEWLIB","topics/capi.md.html#lunatik_ebpf_newlib","Guide · Lunatik C API"],
["Symbols","topics/capi.md.html#symbols","Guide · Lunatik C API"],
["lunatik_lookup","topics/capi.md.html#lunatik_lookup","Guide · Lunatik C API"]
];
