.TH LUNATIK 1 "June 2025" "Lunatik 3.6.2" "User Commands"
.SH NAME
lunatik \- Lua scripting framework for the Linux kernel
.SH SYNOPSIS
.B lunatik
.RI [ script.lua ]
.SH DESCRIPTION
Lunatik provides a way to run Lua scripts inside the Linux kernel, enabling rapid prototyping and extension of kernel functionality. This tool allows you to load and manage kernel Lua scripts.
.SH AUTHOR
Shivam Vashisth <Vashisth11shivam@gmail.com>
.SH HOMEPAGE
https://github.com/luainkernel/lunatik
