/*
* SPDX-FileCopyrightText: (c) 2026 Ring Zero Desenvolvimento de Software LTDA
* SPDX-License-Identifier: MIT OR GPL-2.0-only
*/

/***
* AF_NETLINK kernel socket interface.
* Provides a thin wrapper over kernel AF_NETLINK sockets for use by higher-level
* Lua modules (e.g. `netlink.rt`, `netlink.genl`). Message building and parsing
* is done in Lua using `string.pack` / `string.unpack`.
*
* Two object classes are exposed:
*
* - `netlink`: a sleepable socket for request/response and dump exchanges.
* - `netlink.channel`: a generic netlink multicast family whose `broadcast` is
*   safe from softirq (netfilter hooks, XDP), for kernel-to-userspace telemetry.
*
* Protocol numbers and flags come from the autogenerated `linux.netlink` table.
*
* @module netlink
*/

#define pr_fmt(fmt) KBUILD_MODNAME ": " fmt
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/skbuff.h>
#include <net/netlink.h>
#include <net/genetlink.h>
#include <net/sock.h>

#include <lunatik.h>

#define luanetlink_setmsg(m)	memset(&(m), 0, sizeof(m))

/* generic netlink command and attribute used by netlink.channel broadcasts */
#define LUANETLINK_CMD		1
#define LUANETLINK_PAYLOAD	1

static int luanetlink_new(lua_State *L);
static int luanetlink_channel_new(lua_State *L);

LUNATIK_PRIVATECHECKER(luanetlink_check, struct socket *);

static void luanetlink_release(void *private)
{
	struct socket *sock = (struct socket *)private;

	kernel_sock_shutdown(sock, SHUT_RDWR);
	sock_release(sock);
}

/***
* A sleepable AF_NETLINK socket.
* Returned by `netlink.new()`. Used for request/response and dump exchanges;
* its methods block and must run in a sleepable context.
* @type netlink
*/

/***
* Sends a netlink message to the kernel.
* The caller is responsible for building the complete netlink message
* (including the `nlmsghdr`) before calling this function.
* @function send
* @tparam string msg The raw netlink message bytes.
* @treturn integer Number of bytes sent.
* @raise on send error.
*/
static int luanetlink_send(lua_State *L)
{
	struct socket *sock = luanetlink_check(L, 1);
	size_t len;
	struct kvec vec;
	struct msghdr msg;
	struct sockaddr_nl dst = {
		.nl_family = AF_NETLINK,
		.nl_pid    = 0,
		.nl_groups = 0,
	};
	int ret;

	luanetlink_setmsg(msg);
	msg.msg_name    = &dst;
	msg.msg_namelen = sizeof(dst);

	vec.iov_base = (void *)luaL_checklstring(L, 2, &len);
	vec.iov_len  = len;

	lunatik_tryret(L, ret, kernel_sendmsg, sock, &msg, &vec, 1, len);
	lua_pushinteger(L, ret);
	return 1;
}

/***
* Receives a netlink message from the kernel.
* Blocks until a message arrives (sleepable context only).
* @function recv
* @tparam integer maxlen Maximum number of bytes to receive.
* @treturn string Raw received bytes (may contain one or more `nlmsghdr` messages).
* @raise on receive error.
*/
static int luanetlink_recv(lua_State *L)
{
	struct socket *sock = luanetlink_check(L, 1);
	size_t len = (size_t)luaL_checkinteger(L, 2);
	struct kvec vec;
	struct msghdr msg;
	luaL_Buffer B;
	int ret;

	luanetlink_setmsg(msg);

	vec.iov_base = (void *)luaL_buffinitsize(L, &B, len);
	vec.iov_len  = len;

	lunatik_tryret(L, ret, kernel_recvmsg, sock, &msg, &vec, 1, len, 0);
	luaL_pushresultsize(&B, ret);
	return 1;
}

typedef struct luanetlink_channel_s {
	struct genl_family          family;
	struct genl_multicast_group mcgrp;
	bool                        registered;
} luanetlink_channel_t;

LUNATIK_PRIVATECHECKER(luanetlink_channel_check, luanetlink_channel_t *,
	luaL_argcheck(L, private->registered, ix, LUNATIK_ERR_NULLPTR);)

static void luanetlink_channel_release(void *private)
{
	luanetlink_channel_t *ch = (luanetlink_channel_t *)private;

	if (ch->registered)
		genl_unregister_family(&ch->family);
}

/***
* A generic netlink multicast channel.
* Returned by `netlink.channel()`. Backed by a generic netlink family with one
* multicast group; `broadcast` is safe from softirq (netfilter hooks, XDP) and
* delivers to userspace subscribers of the family's group.
* @type netlink.channel
*/

/***
* Broadcasts a message to all userspace subscribers of the channel's group.
* Safe to call from softirq. Silently ignores the case where no userspace
* process is subscribed (`-ESRCH`).
* @function broadcast
* @tparam string data Raw payload bytes.
* @raise on allocation or send error (other than no subscribers).
*/
static int luanetlink_broadcast(lua_State *L)
{
	luanetlink_channel_t *ch = luanetlink_channel_check(L, 1);
	size_t len;
	const char *data = luaL_checklstring(L, 2, &len);
	struct sk_buff *skb;
	void *hdr;
	int ret;

	skb = genlmsg_new(nla_total_size(len), GFP_ATOMIC);
	if (!skb)
		return lunatik_enomem(L);

	hdr = genlmsg_put(skb, 0, 0, &ch->family, 0, LUANETLINK_CMD);
	if (!hdr || nla_put(skb, LUANETLINK_PAYLOAD, (int)len, data) != 0) {
		nlmsg_free(skb);
		return luaL_error(L, "message too large");
	}
	genlmsg_end(skb, hdr);

	ret = genlmsg_multicast(&ch->family, skb, 0, 0, GFP_ATOMIC);
	if (ret == -ESRCH)
		ret = 0;
	if (ret < 0)
		lunatik_throw(L, ret);
	return 0;
}

static const luaL_Reg luanetlink_lib[] = {
	{"new",     luanetlink_new},
	{"channel", luanetlink_channel_new},
	{NULL, NULL}
};

static const luaL_Reg luanetlink_mt[] = {
	{"__gc",    lunatik_deleteobject},
	{"__close", lunatik_closeobject},
	{"close",   lunatik_closeobject},
	{"send",    luanetlink_send},
	{"recv",    luanetlink_recv},
	{NULL, NULL}
};

static const luaL_Reg luanetlink_channel_mt[] = {
	{"__gc",      lunatik_deleteobject},
	{"broadcast", luanetlink_broadcast},
	{NULL, NULL}
};

LUNATIK_OPENER(netlink);

static const lunatik_class_t luanetlink_class = {
	.name    = "netlink",
	.methods = luanetlink_mt,
	.release = luanetlink_release,
	.opener  = luaopen_netlink,
	.opt     = LUNATIK_OPT_EXTERNAL,
};

static const lunatik_class_t luanetlink_channel_class = {
	.name    = "netlink.channel",
	.methods = luanetlink_channel_mt,
	.release = luanetlink_channel_release,
	.opener  = luaopen_netlink,
	.opt     = LUNATIK_OPT_SOFTIRQ | LUNATIK_OPT_SINGLE,
};

#define luanetlink_newsocket(L)		(lunatik_newobject((L), &luanetlink_class, 0, LUNATIK_OPT_NONE))
#define luanetlink_psocket(object)	((struct socket **)&(object)->private)

/***
* Opens a new AF_NETLINK kernel socket.
* @function new
* @tparam integer proto Netlink protocol (e.g. `linux.netlink.ROUTE`, `linux.netlink.GENERIC`).
* @treturn netlink A new netlink socket object.
* @raise if socket creation or bind fails.
* @within netlink
*/
static int luanetlink_new(lua_State *L)
{
	int proto = (int)luaL_checkinteger(L, 1);
	lunatik_object_t *object = luanetlink_newsocket(L);
	struct socket **psock = luanetlink_psocket(object);
	struct sockaddr_nl addr = {
		.nl_family = AF_NETLINK,
		.nl_pid    = 0,
		.nl_groups = 0,
	};

	lunatik_try(L, sock_create_kern, &init_net, AF_NETLINK, SOCK_RAW, proto, psock);
	lunatik_try(L, kernel_bind, *psock, (struct sockaddr *)&addr, sizeof(addr));
	return 1; /* object */
}

/***
* Creates a generic netlink multicast channel.
* Registers a generic netlink family `name` with a single multicast group (also
* named `name`); userspace resolves the family by name (e.g. via `netlink.genl`)
* to learn the group it must join. Like a netfilter hook, it must be created at
* script load (process context); the returned channel lives for the runtime and
* its `broadcast` may then be called from softirq.
* @function channel
* @tparam string name Generic netlink family name (up to `GENL_NAMSIZ-1` bytes).
* @treturn netlink.channel A new channel object.
* @raise if the name is too long or family registration fails.
* @within netlink
*/
static int luanetlink_channel_new(lua_State *L)
{
	size_t len;
	const char *name = luaL_checklstring(L, 1, &len);
	luaL_argcheck(L, len < GENL_NAMSIZ, 1, "family name too long");
	lunatik_object_t *object = lunatik_newobject(L, &luanetlink_channel_class,
		sizeof(luanetlink_channel_t), LUNATIK_OPT_NONE);
	luanetlink_channel_t *ch = (luanetlink_channel_t *)object->private;

	memcpy(ch->family.name, name, len + 1);
	memcpy(ch->mcgrp.name, name, len + 1);
	ch->family.version  = 1;
	ch->family.module   = THIS_MODULE;
	ch->family.mcgrps   = &ch->mcgrp;
	ch->family.n_mcgrps = 1;

	lunatik_try(L, genl_register_family, &ch->family);
	ch->registered = true;

	lunatik_register(L, -1, object); /* pin: release sleeps, must run at teardown */
	return 1; /* object */
}

LUNATIK_CLASSES(netlink, &luanetlink_class, &luanetlink_channel_class);
LUNATIK_NEWLIB(netlink, luanetlink_lib, luanetlink_classes);

static int __init luanetlink_init(void)
{
	return 0;
}

static void __exit luanetlink_exit(void)
{
}

module_init(luanetlink_init);
module_exit(luanetlink_exit);
MODULE_LICENSE("Dual MIT/GPL");
MODULE_AUTHOR("Lourival Vieira Neto <lourival.neto@ringzero.com.br>");

