/*
* SPDX-FileCopyrightText: (c) 2026 Ring Zero Desenvolvimento de Software LTDA
* SPDX-License-Identifier: MIT OR GPL-2.0-only
*/

/***
* AF_NETLINK kernel socket interface.
* Provides a thin wrapper over kernel AF_NETLINK sockets for use by higher-level
* Lua modules (e.g. `netlink.rt`). Message building and parsing is done in Lua
* using `string.pack` / `string.unpack`; protocol numbers and flags come from
* the autogenerated `linux.netlink` table.
*
* @module netlink
*/

#define pr_fmt(fmt) KBUILD_MODNAME ": " fmt
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/skbuff.h>
#include <net/netlink.h>
#include <net/sock.h>

#include <lunatik.h>

#define luanetlink_setmsg(m)	memset(&(m), 0, sizeof(m))

static int luanetlink_new(lua_State *L);

LUNATIK_PRIVATECHECKER(luanetlink_check, struct socket *);

static void luanetlink_release(void *private)
{
	struct socket *sock = (struct socket *)private;

	kernel_sock_shutdown(sock, SHUT_RDWR);
	sock_release(sock);
}

/***
* A sleepable AF_NETLINK socket.
* Returned by `netlink.new()`. Used for request/response and dump exchanges;
* its methods block and must run in a sleepable context.
* @type netlink
*/

/***
* Sends a netlink message to the kernel.
* The caller is responsible for building the complete netlink message
* (including the `nlmsghdr`) before calling this function.
* @function send
* @tparam string msg The raw netlink message bytes.
* @treturn integer Number of bytes sent.
* @raise on send error.
*/
static int luanetlink_send(lua_State *L)
{
	struct socket *sock = luanetlink_check(L, 1);
	size_t len;
	struct kvec vec;
	struct msghdr msg;
	struct sockaddr_nl dst = {
		.nl_family = AF_NETLINK,
		.nl_pid    = 0,
		.nl_groups = 0,
	};
	int ret;

	luanetlink_setmsg(msg);
	msg.msg_name    = &dst;
	msg.msg_namelen = sizeof(dst);

	vec.iov_base = (void *)luaL_checklstring(L, 2, &len);
	vec.iov_len  = len;

	lunatik_tryret(L, ret, kernel_sendmsg, sock, &msg, &vec, 1, len);
	lua_pushinteger(L, ret);
	return 1;
}

/***
* Receives a netlink message from the kernel.
* Blocks until a message arrives (sleepable context only).
* @function recv
* @tparam integer maxlen Maximum number of bytes to receive.
* @treturn string Raw received bytes (may contain one or more `nlmsghdr` messages).
* @raise on receive error.
*/
static int luanetlink_recv(lua_State *L)
{
	struct socket *sock = luanetlink_check(L, 1);
	size_t len = (size_t)luaL_checkinteger(L, 2);
	struct kvec vec;
	struct msghdr msg;
	luaL_Buffer B;
	int ret;

	luanetlink_setmsg(msg);

	vec.iov_base = (void *)luaL_buffinitsize(L, &B, len);
	vec.iov_len  = len;

	lunatik_tryret(L, ret, kernel_recvmsg, sock, &msg, &vec, 1, len, 0);
	luaL_pushresultsize(&B, ret);
	return 1;
}

static const luaL_Reg luanetlink_lib[] = {
	{"new", luanetlink_new},
	{NULL, NULL}
};

static const luaL_Reg luanetlink_mt[] = {
	{"__gc",    lunatik_deleteobject},
	{"__close", lunatik_closeobject},
	{"close",   lunatik_closeobject},
	{"send",    luanetlink_send},
	{"recv",    luanetlink_recv},
	{NULL, NULL}
};

LUNATIK_OPENER(netlink);

static const lunatik_class_t luanetlink_class = {
	.name    = "netlink",
	.methods = luanetlink_mt,
	.release = luanetlink_release,
	.opener  = luaopen_netlink,
	.opt     = LUNATIK_OPT_EXTERNAL,
};

#define luanetlink_newsocket(L)		(lunatik_newobject((L), &luanetlink_class, 0, LUNATIK_OPT_NONE))
#define luanetlink_psocket(object)	((struct socket **)&(object)->private)

/***
* Opens a new AF_NETLINK kernel socket.
* @function new
* @tparam integer proto Netlink protocol (e.g. `linux.netlink.ROUTE`, `linux.netlink.GENERIC`).
* @treturn netlink A new netlink socket object.
* @raise if socket creation or bind fails.
* @within netlink
*/
static int luanetlink_new(lua_State *L)
{
	int proto = (int)luaL_checkinteger(L, 1);
	lunatik_object_t *object = luanetlink_newsocket(L);
	struct socket **psock = luanetlink_psocket(object);
	struct sockaddr_nl addr = {
		.nl_family = AF_NETLINK,
		.nl_pid    = 0,
		.nl_groups = 0,
	};

	lunatik_try(L, sock_create_kern, &init_net, AF_NETLINK, SOCK_RAW, proto, psock);
	lunatik_try(L, kernel_bind, *psock, (struct sockaddr *)&addr, sizeof(addr));
	return 1; /* object */
}

LUNATIK_CLASSES(netlink, &luanetlink_class);
LUNATIK_NEWLIB(netlink, luanetlink_lib, luanetlink_classes);

static int __init luanetlink_init(void)
{
	return 0;
}

static void __exit luanetlink_exit(void)
{
}

module_init(luanetlink_init);
module_exit(luanetlink_exit);
MODULE_LICENSE("Dual MIT/GPL");
MODULE_AUTHOR("Lourival Vieira Neto <lourival.neto@ringzero.com.br>");

