/*
* SPDX-FileCopyrightText: (c) 2024-2026 Ring Zero Desenvolvimento de Software LTDA
* SPDX-License-Identifier: MIT OR GPL-2.0-only
*/

/***
* Accessing kernel system call information.
* Retrieves the kernel address of a system call given its number.
* System call numbers are available as a separate autogenerated table at
* `linux.syscall.numbers`.
* This is particularly useful for kernel probing (see `probe`)
* or other low-level kernel interactions.
*
* @module syscall
*/

#define pr_fmt(fmt) KBUILD_MODNAME ": " fmt
#include <linux/kprobes.h>

#include <lunatik.h>

static unsigned long **luasyscall_table;

/***
* Retrieves the kernel address of a system call.
* @function address
* @tparam integer syscall_number system call number (e.g., `__NR_openat`).
* @treturn lightuserdata kernel address of the system call entry point, or `nil` if the number is invalid or the address cannot be determined.
* @raise Error if `syscall_number` is out of bounds.
* @usage
*   local syscall = require("syscall")
*   local numbers = require("linux.syscall").numbers
*   local openat_addr = syscall.address(numbers.openat)
* @within syscall
*/
static int luasyscall_address(lua_State *L)
{
	lua_Integer nr = luaL_checkinteger(L, 1);
	luaL_argcheck(L, nr >= 0 && nr < __NR_syscalls, 1, "out of bounds");
	lua_pushlightuserdata(L, (void *)luasyscall_table[nr]);
	return 1;
}

static const luaL_Reg luasyscall_lib[] = {
	{"address", luasyscall_address},
	{NULL, NULL}
};

LUNATIK_NEWLIB(syscall, luasyscall_lib, NULL);

static int __init luasyscall_init(void)
{
	if ((luasyscall_table = (unsigned long **)lunatik_lookup("sys_call_table")) == NULL)
		return -ENXIO;
	return 0;
}

static void __exit luasyscall_exit(void)
{
}

module_init(luasyscall_init);
module_exit(luasyscall_exit);
MODULE_LICENSE("Dual MIT/GPL");
MODULE_AUTHOR("Lourival Vieira Neto <lourival.neto@ringzero.com.br>");

