--
-- SPDX-FileCopyrightText: (c) 2026 Ring Zero Desenvolvimento de Software LTDA
-- SPDX-License-Identifier: MIT OR GPL-2.0-only
--

---
-- Binary codec for fixed C struct layouts. Calling the module on a layout
-- descriptor (as generated by autogen, e.g.
-- `require("linux.netlink").layout.nlmsghdr`) derives a `string.pack` format
-- once and returns a codec exposing `pack`/`unpack`/`size`, so callers never
-- hand-write the byte layout.
-- @module struct
-- @usage
-- local struct = require("struct")
-- local nlmsghdr = struct(require("linux.netlink").layout.nlmsghdr)
-- local bytes = nlmsghdr:pack(len, mtype, flags, seq, pid)
-- local len, mtype = nlmsghdr:unpack(bytes)

local struct = {}
struct.__index = struct

-- Derive the `string.pack` format from a layout: each field as `I<size>` (or
-- `i<size>` when signed), with `x` filling inter-field padding and the tail
-- up to `size`. Native byte order (`=`) for the host-endian struct.
local function build_format(layout)
	local fields = table.move(layout.fields, 1, #layout.fields, 1, {})
	table.sort(fields, function(a, b) return a.offset < b.offset end)
	local out, pos = {"="}, 0
	for _, f in ipairs(fields) do
		if f.offset > pos then table.insert(out, ("x"):rep(f.offset - pos)) end
		table.insert(out, (f.signed and "i" or "I") .. f.size)
		pos = f.offset + f.size
	end
	if layout.size > pos then table.insert(out, ("x"):rep(layout.size - pos)) end
	return table.concat(out)
end

---
-- Serializes the field values (in offset order) into the struct's bytes.
-- @function struct:pack
-- @param ... the field values
-- @treturn string
function struct:pack(...)
	return string.pack(self.format, ...)
end

---
-- Deserializes the struct's fields from a buffer.
-- @function struct:unpack
-- @tparam string buf
-- @tparam[opt] integer pos starting offset (1-based)
-- @return the field values in offset order, then the position past the struct
function struct:unpack(buf, pos)
	return string.unpack(self.format, buf, pos)
end

---
-- Builds a codec from a layout descriptor.
-- @tparam table layout `{ size = bytes, fields = { {name, offset, size, signed}, ... } }`
-- @treturn struct a codec exposing `:pack`, `:unpack` and a `size` field.
return function(layout)
	local format = build_format(layout)
	assert(string.packsize(format) == layout.size,
		"struct: derived format does not match the layout size (overlapping fields?)")
	return setmetatable({ format = format, size = layout.size }, struct)
end

