# zlib

klib-y := adler32.o compress.o crc32.o gzio.o
klib-y += uncompr.o deflate.o trees.o zutil.o
klib-y += inflate.o infback.o inftrees.o inffast.o

# zlib specific flag
EXTRA_KLIBCCFLAGS := -DDYNAMIC_CRC_TABLE

# Suppress implicit-fallthrough warning for state machine cases
# where this is intentional
EXTRA_KLIBCCFLAGS += $(call cc-disable-warning,implicit-fallthrough)
